In [ ]:
!pip install -q huggingface_hub
!pip install -U "transformers>=4.40.0"


from huggingface_hub import login

# Option 1: Hard-code your token (not recommended to share)
# token = "hf_XXXXXXXXXXXXXXXXXXXXXXXXXXXX"
# login(token=token)

# Option 2: Enter securely at runtime
token = input("Paste your Hugging Face access token: ").strip()
login(token=token)
print("Logged in to Hugging Face Hub.")

In [ ]:
# ============================================================================
# PEFT / LoRA FINE-TUNING — MULTILINGUAL TEXT CLASSIFICATION
# ALL 3 MODELS × ALL 3 LANGUAGES
#
# Models  : xlm-roberta-base | ai4bharat/indic-bert | microsoft/mdeberta-v3-base
# Languages: Hindi | Tamil | Telugu
# Metrics : Accuracy, F1 Macro, per-class Precision / Recall / F1
# ============================================================================

# INSTALLS (uncomment if needed in Colab)
# !pip install transformers peft accelerate datasets scikit-learn openpyxl tqdm -q

# ============================================================================
# SECTION 1 — IMPORTS
# ============================================================================
import os
import json
import random
import warnings

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F

from datasets import Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer,
    TrainerCallback,
)
from peft import (
    LoraConfig,
    get_peft_model,
    TaskType,
)
from huggingface_hub import login

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    precision_recall_fscore_support,
    classification_report,
    confusion_matrix,
    precision_recall_curve,
)


warnings.filterwarnings("ignore")

os.environ["HF_HOME"] = "/content/hf_cache"

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

if "HF_TOKEN" in os.environ:
    login(token=os.environ["HF_TOKEN"])
    print("✓ Logged in to Hugging Face Hub.")
else:
    print("⚠️  HF_TOKEN not set. Gated models may not be accessible.")



# ============================================================================
# SECTION 2 — REPRODUCIBILITY
# ============================================================================
def set_seed(seed: int = 42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
        torch.backends.cudnn.deterministic = True
        torch.backends.cudnn.benchmark = False
# ============================================================================
# SECTION 3 — CONFIGURATION
# ============================================================================

# --- Datasets (one per language) ---
DATASETS = {
    'Hindi' : '/content/drive/MyDrive/Datasets/Hindi_dataset/hindi_filtered_new_criteria.xlsx',
    'Tamil' : '/content/drive/MyDrive/Datasets/Tamil_dataset/filtered_dataset_tamil.xlsx',
    'Telugu': '/content/drive/MyDrive/Datasets/Telugu_dataset/filtered_dataset_telugu.xlsx',
}

# --- Models with architecture-specific LoRA target modules ---
MODELS = {
    'mdeberta': {
        'model_id'       : 'microsoft/mdeberta-v3-base',
        'target_modules' : ['query_proj', 'value_proj'],            # DeBERTa attention
    },

    'indicbert': {
        'model_id'       : 'ai4bharat/indic-bert',
        'target_modules' : ['query', 'key', 'value', 'dense'],      # ALBERT shared layers
    },
    'xlm-roberta': {
        'model_id'       : 'xlm-roberta-base',
        'target_modules' : ['query', 'value'],                      # RoBERTa attention
    },


}

TEXT_COL        = 'text'
LABEL_COL       = 'labels'
BASE_OUTPUT_DIR = '/content/drive/MyDrive/Models'

# --- Hyperparameter grid ---
# Shifted upward — lower LRs cause collapse on IndicBERT/mDeBERTa
BATCH_SIZES    = [32, 64]
LEARNING_RATES = [3e-4, 5e-4, 7e-4]

# --- Training config ---
MAX_LEN        = 128
NUM_EPOCHS     = 5
GAMMA          = 2.5    # Focal Loss focusing parameter
MINORITY_BOOST = 1.0    # Set to 1.0 — Focal Loss alone handles imbalance
                        # (combining both caused gradient collapse on small models)
TARGET_RECALL  = 0.95   # Class 1 recall target for early stopping

# --- Train / Val / Test split ---
TRAIN_RATIO = 0.70
VAL_RATIO   = 0.15
TEST_RATIO  = 0.15

# --- LoRA config ---
LORA_R       = 16
LORA_ALPHA   = 32
LORA_DROPOUT = 0.1
# ============================================================================
# SECTION 4 — FOCAL LOSS
# ============================================================================
class FocalLoss(nn.Module):
    """
    Focal Loss — down-weights easy examples, focuses on hard minority samples.
    alpha  : per-class weights tensor
    gamma  : focusing parameter (higher = more focus on hard examples)
    """
    def __init__(self, alpha=None, gamma=2.0, reduction='mean'):
        super().__init__()
        self.alpha     = alpha
        self.gamma     = gamma
        self.reduction = reduction

    def forward(self, inputs, targets):
        ce_loss    = F.cross_entropy(inputs, targets, reduction='none', weight=self.alpha)
        pt         = torch.exp(-ce_loss)
        focal_loss = ((1 - pt) ** self.gamma) * ce_loss

        if self.reduction == 'mean':
            return focal_loss.mean()
        elif self.reduction == 'sum':
            return focal_loss.sum()
        return focal_loss


# ============================================================================
# SECTION 5 — CUSTOM CALLBACK: RECALL EARLY STOPPING
# ============================================================================
class RecallEarlyStopping(TrainerCallback):
    """Stop training as soon as Class 1 recall reaches TARGET_RECALL."""

    def __init__(self, target_recall=0.95, patience=2):
        super().__init__()
        self.target_recall    = target_recall
        self.patience         = patience
        self.patience_counter = 0
        self.best_recall      = 0.0

    def on_evaluate(self, args, state, control, metrics=None, **kwargs):
        if metrics is None:
            return control

        recall_class_1 = metrics.get("eval_recall_class_1", 0)

        if recall_class_1 >= self.target_recall:
            control.should_training_stop = True
            control.should_save          = True

        if recall_class_1 > self.best_recall:
            self.best_recall      = recall_class_1
            self.patience_counter = 0
        else:
            self.patience_counter += 1
            if self.patience_counter >= self.patience:
        return control


# ============================================================================
# SECTION 6 — FOCAL LOSS TRAINER
# ============================================================================
class FocalLossTrainer(Trainer):
    """HuggingFace Trainer that replaces cross-entropy with Focal Loss."""

    def __init__(self, *args, class_weights=None, gamma=2.0, **kwargs):
        super().__init__(*args, **kwargs)
        if class_weights is not None:
            self.class_weights = torch.tensor(
                class_weights, dtype=torch.float
            ).to(self.args.device)
        else:
            self.class_weights = None
        self.gamma = gamma
    def compute_loss(self, model, inputs, return_outputs=False, num_items_in_batch=None):
        labels  = inputs.pop("labels")
        outputs = model(**inputs)
        logits  = outputs.logits

        loss_fct = FocalLoss(alpha=self.class_weights, gamma=self.gamma)
        loss     = loss_fct(logits, labels)

        return (loss, outputs) if return_outputs else loss


# ============================================================================
# SECTION 7 — DATASET LOADING & STRATIFIED SPLIT
# ============================================================================
def load_and_split(
    file_path,
    text_col=TEXT_COL,
    label_col=LABEL_COL,
    train_ratio=TRAIN_RATIO,
    val_ratio=VAL_RATIO,
    test_ratio=TEST_RATIO,
    random_state=42,
    save_dir='./splits',
):
    print("=" * 60)

    if file_path.endswith(('.xlsx', '.xls')):
        df = pd.read_excel(file_path)
    elif file_path.endswith('.csv'):
        df = pd.read_csv(file_path)
    else:
        raise ValueError(f"Unsupported format: {file_path}")

    df = df[[text_col, label_col]].dropna().reset_index(drop=True)

    print(f"\n📊 Original dataset : {len(df):,} rows")
    class_counts = df[label_col].value_counts().sort_index()
    for lbl, cnt in class_counts.items():
        print(f"   Class {lbl}: {cnt:,}  ({cnt/len(df)*100:.1f}%)")

    imbalance = class_counts.max() / class_counts.min()
    if imbalance > 3:
    # Stratified splits
    train_val, test_df = train_test_split(
        df, test_size=test_ratio, random_state=random_state, stratify=df[label_col]
    )
    adjusted_val = val_ratio / (train_ratio + val_ratio)
    train_df, val_df = train_test_split(
        train_val, test_size=adjusted_val, random_state=random_state,
        stratify=train_val[label_col]
    )

    for name, split in [("TRAIN", train_df), ("VAL", val_df), ("TEST", test_df)]:
        counts = split[label_col].value_counts().sort_index()
        print(f"\n   {name} ({len(split):,}):")
        for lbl, cnt in counts.items():
            print(f"      Class {lbl}: {cnt:,}  ({cnt/len(split)*100:.1f}%)")

    # Class weights with configurable minority boost
    labels_arr = train_df[label_col].values
    unique_cls = np.unique(labels_arr)
    n          = len(labels_arr)
    weights    = [n / (len(unique_cls) * np.sum(labels_arr == c)) for c in sorted(unique_cls)]
    weights    = [w / min(weights) for w in weights]
    min_idx    = int(np.argmin([np.sum(labels_arr == c) for c in sorted(unique_cls)]))
    weights[min_idx] *= MINORITY_BOOST
    os.makedirs(save_dir, exist_ok=True)
    train_df.to_csv(f"{save_dir}/train.csv", index=False)
    val_df.to_csv(f"{save_dir}/val.csv",     index=False)
    test_df.to_csv(f"{save_dir}/test.csv",   index=False)
    with open(f"{save_dir}/class_weights.json", "w") as f:
        json.dump({"class_weights": weights}, f, indent=2)
    return train_df, val_df, test_df, weights


# ============================================================================
# SECTION 8 — TOKENIZATION HELPER
# ============================================================================
def tokenize_datasets(train_df, val_df, test_df, tokenizer, text_col, label_col):
    """Tokenize all three splits and return HF Dataset objects."""

    def df_to_hf(df):
        return Dataset.from_dict({
            'text' : df[text_col].tolist(),
            'label': df[label_col].tolist(),
        })

    def tokenize_fn(examples):
        return tokenizer(
            examples['text'],
            padding    = 'max_length',
            truncation = True,
            max_length = MAX_LEN,
        )
    train_ds = df_to_hf(train_df).map(tokenize_fn, batched=True).remove_columns(['text'])
    val_ds   = df_to_hf(val_df).map(tokenize_fn,   batched=True).remove_columns(['text'])
    test_ds  = df_to_hf(test_df).map(tokenize_fn,  batched=True).remove_columns(['text'])

    for ds in [train_ds, val_ds, test_ds]:
        ds.set_format('torch')

    print(f"   ✅ Train : {len(train_ds):,}   Val : {len(val_ds):,}   Test : {len(test_ds):,}")
    return train_ds, val_ds, test_ds


# ============================================================================
# SECTION 9 — METRICS
# ============================================================================
def compute_metrics(eval_pred):
    """
    Accuracy, F1 Macro, and per-class Precision / Recall / F1.
    recall_class_1 is monitored by RecallEarlyStopping.
    """
    logits, labels = eval_pred
    predictions    = np.argmax(logits, axis=-1)

    accuracy = accuracy_score(labels, predictions)
    f1_macro = f1_score(labels, predictions, average='macro')
    precision, recall, f1, _ = precision_recall_fscore_support(
        labels, predictions, average=None, labels=[0, 1]
    )

    return {
        'accuracy'          : accuracy,
        'f1_macro'          : f1_macro,
        'precision_class_0' : precision[0],
        'recall_class_0'    : recall[0],
        'f1_class_0'        : f1[0],
        'precision_class_1' : precision[1],
        'recall_class_1'    : recall[1],   # ← used by RecallEarlyStopping
        'f1_class_1'        : f1[1],
    }


# ============================================================================
# SECTION 10 — BUILD LORA MODEL
# ============================================================================
def build_lora_model(model_id, target_modules, num_labels=2):
    """
    Load a base classification model and wrap it with LoRA adapters.
    target_modules must match the architecture:
      - xlm-roberta : ['query', 'value']
      - indic-bert  : ['query', 'key', 'value', 'dense']  (ALBERT shared layers)
      - mdeberta    : ['query_proj', 'value_proj']
    """
    hf_token   = os.environ.get("HF_TOKEN")
    base_model = AutoModelForSequenceClassification.from_pretrained(
        model_id, num_labels=num_labels, token=hf_token
    )

    lora_cfg = LoraConfig(
        task_type      = TaskType.SEQ_CLS,
        r              = LORA_R,
        lora_alpha     = LORA_ALPHA,
        lora_dropout   = LORA_DROPOUT,
        bias           = 'none',
        target_modules = target_modules,
    )

    # Build once and print — do NOT call get_peft_model twice
    model = get_peft_model(base_model, lora_cfg)
    return model


# ============================================================================
# SECTION 11 — THRESHOLD ADJUSTMENT
# ============================================================================
def find_and_apply_optimal_threshold(trainer, val_dataset, test_dataset,
                                     target_recall=0.95):
    """
    Find the lowest threshold on the validation set that meets target recall,
    then evaluate the test set at that threshold.
    """
    print("\n" + "=" * 60)
    print("🎯 THRESHOLD OPTIMIZATION FOR 95% RECALL")
    print("=" * 60)

    val_out    = trainer.predict(val_dataset)
    val_probs  = torch.softmax(torch.tensor(val_out.predictions), dim=1)[:, 1].numpy()
    val_labels = val_out.label_ids

    precisions, recalls, thresholds = precision_recall_curve(val_labels, val_probs, pos_label=1)
    idx = np.where(recalls >= target_recall)[0]

    if len(idx) == 0:
        print(f"❌ Cannot reach {target_recall*100:.0f}% recall on validation set.")
        return None

    best_idx = idx[np.argmax(precisions[idx])]
    opt_thr  = thresholds[best_idx]

    test_out    = trainer.predict(test_dataset)
    test_probs  = torch.softmax(torch.tensor(test_out.predictions), dim=1)[:, 1].numpy()
    test_labels = test_out.label_ids
    test_preds  = (test_probs >= opt_thr).astype(int)

    acc = accuracy_score(test_labels, test_preds)
    precision, recall, f1, _ = precision_recall_fscore_support(
        test_labels, test_preds, average=None, labels=[0, 1]
    )

    print(f"\n📊 Optimal threshold : {opt_thr:.4f}")
    print(f"   Accuracy          : {acc:.4f}")
    print(f"   Class 0 — Prec: {precision[0]:.4f}  Rec: {recall[0]:.4f}  F1: {f1[0]:.4f}")
    print(f"   Class 1 — Prec: {precision[1]:.4f}  Rec: {recall[1]:.4f}  "
          f"F1: {f1[1]:.4f}  "
          f"{'✅ MEETS TARGET!' if recall[1] >= target_recall else '⚠️ Below target'}")

    cm = confusion_matrix(test_labels, test_preds)
    print(f"\n   Confusion Matrix:\n{cm}")
    print(f"   TN:{cm[0,0]}  FP:{cm[0,1]}  FN:{cm[1,0]}  TP:{cm[1,1]}")
    print("\n" + classification_report(test_labels, test_preds, digits=4))

    return {
        'threshold'        : float(opt_thr),
        'accuracy'         : acc,
        'precision_class_0': precision[0], 'recall_class_0': recall[0], 'f1_class_0': f1[0],
        'precision_class_1': precision[1], 'recall_class_1': recall[1], 'f1_class_1': f1[1],
        'confusion_matrix' : cm,
    }


# ============================================================================
# SECTION 12 — SINGLE TRAINING RUN
# ============================================================================
def run_single_training(
    train_ds, val_ds, test_ds,
    class_weights,
    lr, batch_size,
    run_output_dir,
    model_id,
    target_modules,
):
    """Build a fresh LoRA model, train it, evaluate on test set, return results."""
    # Fresh model for every hyperparameter combination
    model = build_lora_model(model_id, target_modules, num_labels=2)
    is_mdeberta = 'deberta' in model_id.lower()

    training_args = TrainingArguments(
        output_dir                  = run_output_dir,
        eval_strategy               = 'epoch',
        save_strategy               = 'epoch',
        learning_rate               = lr,
        per_device_train_batch_size = batch_size,
        per_device_eval_batch_size  = batch_size,
        num_train_epochs            = NUM_EPOCHS,
        warmup_ratio                = 0.05,
        lr_scheduler_type           = 'cosine',
        weight_decay                = 0.01,
        max_grad_norm               = 1.0,
        logging_steps               = 10,
        save_total_limit            = 2,
        load_best_model_at_end      = True,
        metric_for_best_model       = 'recall_class_1',
        greater_is_better           = True,
        report_to                   = 'none',
        #fp16                        = torch.cuda.is_available(),
        fp16 = torch.cuda.is_available() and not is_mdeberta,
        bf16 = torch.cuda.is_available() and is_mdeberta,
    )

    hf_token  = os.environ.get("HF_TOKEN")
    tokenizer = AutoTokenizer.from_pretrained(model_id, token=hf_token)

    trainer = FocalLossTrainer(
        model            = model,
        args             = training_args,
        train_dataset    = train_ds,
        eval_dataset     = val_ds,
        processing_class = tokenizer,       # replaces deprecated 'tokenizer='
        compute_metrics  = compute_metrics,
        class_weights    = class_weights,
        gamma            = GAMMA,
        callbacks        = [
            RecallEarlyStopping(target_recall=TARGET_RECALL, patience=2),
        ],
    )

    train_result = trainer.train()

    # Evaluate on test set
    pred_output = trainer.predict(test_ds)
    logits      = pred_output.predictions
    labels      = pred_output.label_ids
    predictions = np.argmax(logits, axis=-1)

    accuracy = accuracy_score(labels, predictions)
    f1_macro = f1_score(labels, predictions, average='macro')
    precision, recall, f1, _ = precision_recall_fscore_support(
        labels, predictions, average=None, labels=[0, 1]
    )
    print("\n" + "-" * 60)
    print(classification_report(labels, predictions, digits=4))

    return {
        'lr'                : lr,
        'batch_size'        : batch_size,
        'accuracy'          : accuracy,
        'f1_macro'          : f1_macro,
        'precision_class_0' : float(precision[0]),
        'recall_class_0'    : float(recall[0]),
        'f1_class_0'        : float(f1[0]),
        'precision_class_1' : float(precision[1]),
        'recall_class_1'    : float(recall[1]),
        'f1_class_1'        : float(f1[1]),
        'trainer'           : trainer,
        'val_ds'            : val_ds,
        'test_ds'           : test_ds,
    }


# ============================================================================
# SECTION 13 — SINGLE LANGUAGE × MODEL PIPELINE
# ============================================================================
def run_experiment(lang, model_key, train_ds, val_ds, test_ds, class_weights):
    """
    Run the full grid search for one language + model combination.
    Returns list of all run results and the best run dict.
    """
    model_cfg      = MODELS[model_key]
    model_id       = model_cfg['model_id']
    target_modules = model_cfg['target_modules']
    output_dir     = os.path.join(BASE_OUTPUT_DIR, f'{lang}_{model_key}_lora')
    all_results = []
    best_recall = -1.0
    best_run    = None

    for lr in LEARNING_RATES:
        for bs in BATCH_SIZES:
            run_dir = os.path.join(output_dir, f'tmp_lr{lr}_bs{bs}')
            os.makedirs(run_dir, exist_ok=True)

            results = run_single_training(
                train_ds       = train_ds,
                val_ds         = val_ds,
                test_ds        = test_ds,
                class_weights  = class_weights,
                lr             = lr,
                batch_size     = bs,
                run_output_dir = run_dir,
                model_id       = model_id,
                target_modules = target_modules,
            )
            all_results.append(results)

            if results['recall_class_1'] > best_recall:
                best_recall = results['recall_class_1']
                best_run    = results

    # Threshold tuning if best recall is close but not yet at target
    if best_run['recall_class_1'] < TARGET_RECALL and best_run['recall_class_1'] >= 0.90:
        print("\n🔧 Attempting threshold adjustment to reach 95% recall...")
        tuned = find_and_apply_optimal_threshold(
            best_run['trainer'],
            best_run['val_ds'],
            best_run['test_ds'],
            target_recall=TARGET_RECALL,
        )
        if tuned:
            best_run.update({
                'recall_class_1'    : tuned['recall_class_1'],
                'precision_class_1' : tuned['precision_class_1'],
                'f1_class_1'        : tuned['f1_class_1'],
                'threshold'         : tuned['threshold'],
            })

    # Print grid search summary
    print("\n" + "=" * 60)
    print(f"📊 GRID SEARCH SUMMARY — {lang.upper()} / {model_key.upper()}")
    print("=" * 60)
    rows = [{
        'LR'            : r['lr'],
        'Batch Size'    : r['batch_size'],
        'Accuracy'      : f"{r['accuracy']:.4f}",
        'F1 Macro'      : f"{r['f1_macro']:.4f}",
        'Recall (C1)'   : f"{r['recall_class_1']:.4f}",
        'F1 (C1)'       : f"{r['f1_class_1']:.4f}",
        'Precision (C1)': f"{r['precision_class_1']:.4f}",
    } for r in all_results]
    print(pd.DataFrame(rows).to_string(index=False))

    # Save CSV
    csv_path = f'lora_results_{lang}_{model_key}.csv'
    if 'threshold' in best_run:
        print(f"   Applied threshold : {best_run['threshold']:.4f}")

    # Save best model
    save_dir = os.path.join(output_dir, f'{lang}_{model_key}_best')
    os.makedirs(save_dir, exist_ok=True)
    best_run['trainer'].model.save_pretrained(save_dir)
    hf_token  = os.environ.get("HF_TOKEN")
    tokenizer = AutoTokenizer.from_pretrained(model_id, token=hf_token)
    tokenizer.save_pretrained(save_dir)

    meta = {
        'language'       : lang,
        'model_key'      : model_key,
        'model_id'       : model_id,
        'lora_r'         : LORA_R,
        'lora_alpha'     : LORA_ALPHA,
        'gamma'          : GAMMA,
        'minority_boost' : MINORITY_BOOST,
        'class_weights'  : class_weights,
        'best_lr'        : best_run['lr'],
        'best_batch_size': best_run['batch_size'],
        'accuracy'       : best_run['accuracy'],
        'f1_macro'       : best_run['f1_macro'],
        'recall_class_1' : best_run['recall_class_1'],
        'f1_class_1'     : best_run['f1_class_1'],
    }
    if 'threshold' in best_run:
        meta['threshold'] = best_run['threshold']

    with open(f"{save_dir}/lora_meta.json", 'w') as f:
        json.dump(meta, f, indent=2)
    return all_results, best_run


# ============================================================================
# SECTION 14 — RUN ALL LANGUAGES × ALL MODELS
# ============================================================================
if __name__ == '__main__':
    from google.colab import drive
    drive.mount('/content/drive')

    # Master results table across all 9 experiments
    master_rows    = []
    all_experiment_results = {}

    for lang, dataset_path in DATASETS.items():

        if not os.path.exists(dataset_path):
            print(f"\n⚠️  Dataset not found for {lang}: {dataset_path} — skipping.")
            continue
        # Load & split ONCE per language (shared across all 3 models)
        train_df, val_df, test_df, class_weights = load_and_split(
            file_path = dataset_path,
            text_col  = TEXT_COL,
            label_col = LABEL_COL,
            save_dir  = os.path.join(BASE_OUTPUT_DIR, f'splits_{lang.lower()}'),
        )

        for model_key, model_cfg in MODELS.items():
            model_id  = model_cfg['model_id']
            hf_token  = os.environ.get("HF_TOKEN")

            # Tokenize fresh for each model (different tokenizers)
            tokenizer = AutoTokenizer.from_pretrained(model_id, token=hf_token)
            train_ds, val_ds, test_ds = tokenize_datasets(
                train_df, val_df, test_df, tokenizer, TEXT_COL, LABEL_COL
            )

            # Run grid search for this language × model
            all_results, best_run = run_experiment(
                lang          = lang,
                model_key     = model_key,
                train_ds      = train_ds,
                val_ds        = val_ds,
                test_ds       = test_ds,
                class_weights = class_weights,
            )

            all_experiment_results[f'{lang}_{model_key}'] = best_run

            # Append to master results
            for r in all_results:
                master_rows.append({
                    'Language'      : lang,
                    'Model'         : model_key,
                    'LR'            : r['lr'],
                    'Batch Size'    : r['batch_size'],
                    'Accuracy'      : round(r['accuracy'],    4),
                    'F1 Macro'      : round(r['f1_macro'],    4),
                    'Precision C0'  : round(r['precision_class_0'], 4),
                    'Recall C0'     : round(r['recall_class_0'],    4),
                    'F1 C0'         : round(r['f1_class_0'],        4),
                    'Precision C1'  : round(r['precision_class_1'], 4),
                    'Recall C1'     : round(r['recall_class_1'],    4),
                    'F1 C1'         : round(r['f1_class_1'],        4),
                    'Meets Target'  : '✅' if r['recall_class_1'] >= TARGET_RECALL else '⚠️',
                })

    # Save master CSV covering all 9 experiments
    master_df = pd.DataFrame(master_rows)
    master_csv = os.path.join(BASE_OUTPUT_DIR, 'lora_all_results_master.csv')
    master_df.to_csv(master_csv, index=False)
    print(f"\n💾 Master results saved to: {master_csv}")

GPU: NVIDIA A100-SXM4-40GB
VRAM: 42.4 GB
⚠️  HF_TOKEN not set. Gated models may not be accessible.
✓ All imports successful.
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

============================================================
  LOADING DATASET FOR LANGUAGE: Hindi
============================================================

============================================================
📂 DATASET LOADING WITH STRATIFICATION
============================================================

📊 Original dataset : 4,037 rows
   Class 0: 3,559  (88.2%)
   Class 1: 478  (11.8%)

   ⚠️  Imbalance ratio: 7.45:1  → Focal Loss will help

   TRAIN (2,825):
      Class 0: 2,491  (88.2%)
      Class 1: 334  (11.8%)

   VAL (606):
      Class 0: 534  (88.1%)
      Class 1: 72  (11.9%)

   TEST (606):
      Class 0: 534  (88.1%)
      Class 1: 72  (11.9%)

📊 Class weights (minority boost=1.0×): [np.float64(1.0), np.float64(7.45808383233533)]
💾 Splits saved to /content/drive/MyDrive/Models/splits_hindi/

config.json:   0%|          | 0.00/579 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

spm.model:   0%|          | 0.00/4.31M [00:00<?, ?B/s]

🔄 Tokenizing datasets...

Map:   0%|          | 0/2825 [00:00<?, ? examples/s]

Map:   0%|          | 0/606 [00:00<?, ? examples/s]

Map:   0%|          | 0/606 [00:00<?, ? examples/s]

   ✅ Train : 2,825   Val : 606   Test : 606

############################################################
# LANGUAGE : Hindi  |  MODEL : mdeberta
# microsoft/mdeberta-v3-base
# Batch sizes    : [32, 64]
# Learning rates : [0.0003, 0.0005, 0.0007]
# Focal gamma    : 2.5  |  Minority boost: 1.0×
# Early stop on Class-1 recall >= 95%
############################################################

🔧 LR=0.0003  |  batch_size=32

pytorch_model.bin:   0%|          | 0.00/1.33G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/198 [00:00<?, ?it/s]

DebertaV2ForSequenceClassification LOAD REPORT from: microsoft/mdeberta-v3-base
Key                                        | Status     |
-------------------------------------------+------------+-
mask_predictions.dense.weight              | UNEXPECTED |
mask_predictions.LayerNorm.weight          | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.bias      | UNEXPECTED |
mask_predictions.dense.bias                | UNEXPECTED |
mask_predictions.classifier.bias           | UNEXPECTED |
lm_predictions.lm_head.bias                | UNEXPECTED |
mask_predictions.classifier.weight         | UNEXPECTED |
lm_predictions.lm_head.dense.weight        | UNEXPECTED |
lm_predictions.lm_head.dense.bias          | UNEXPECTED |
mask_predictions.LayerNorm.bias            | UNEXPECTED |
deberta.embeddings.word_embeddings._weight | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.weight    | UNEXPECTED |
pooler.dense.weight                        | MISSING    |
pooler.dense.bias                          | MISSING    |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

model.safetensors:   0%|          | 0.00/1.33G [00:00<?, ?B/s]

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 591,362 || all params: 279,402,244 || trainable%: 0.2117

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 2, 'bos_token_id': 1}.

   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(7.45808383233533)]
🚀 Training...

⏸️  Recall hasn't improved for 2 evals. Best: 0.9167

⏸️  Recall hasn't improved for 2 evals. Best: 0.9167

⏸️  Recall hasn't improved for 2 evals. Best: 0.9167
   ✅ Training done — loss: 0.1768

📊 Test Set Results:
   Accuracy   : 0.9785
   F1 Macro   : 0.9485
   Class 0 — Prec: 0.9869  Rec: 0.9888  F1: 0.9878
   Class 1 — Prec: 0.9155  Rec: 0.9028  F1: 0.9091
   ⚠️  Class 1 recall 0.9028 below 95% target

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9869    0.9888    0.9878       534
           1     0.9155    0.9028    0.9091        72

    accuracy                         0.9785       606
   macro avg     0.9512    0.9458    0.9485       606
weighted avg     0.9784    0.9785    0.9785       606


🔧 LR=0.0003  |  batch_size=64

Loading weights:   0%|          | 0/198 [00:00<?, ?it/s]

DebertaV2ForSequenceClassification LOAD REPORT from: microsoft/mdeberta-v3-base
Key                                        | Status     |
-------------------------------------------+------------+-
mask_predictions.dense.weight              | UNEXPECTED |
mask_predictions.LayerNorm.weight          | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.bias      | UNEXPECTED |
mask_predictions.dense.bias                | UNEXPECTED |
mask_predictions.classifier.bias           | UNEXPECTED |
lm_predictions.lm_head.bias                | UNEXPECTED |
mask_predictions.classifier.weight         | UNEXPECTED |
lm_predictions.lm_head.dense.weight        | UNEXPECTED |
lm_predictions.lm_head.dense.bias          | UNEXPECTED |
mask_predictions.LayerNorm.bias            | UNEXPECTED |
deberta.embeddings.word_embeddings._weight | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.weight    | UNEXPECTED |
pooler.dense.weight                        | MISSING    |
pooler.dense.bias                          | MISSING    |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 591,362 || all params: 279,402,244 || trainable%: 0.2117

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 2, 'bos_token_id': 1}.

   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(7.45808383233533)]
🚀 Training...

⏸️  Recall hasn't improved for 2 evals. Best: 0.9306

⏸️  Recall hasn't improved for 2 evals. Best: 0.9306
   ✅ Training done — loss: 0.2020

📊 Test Set Results:
   Accuracy   : 0.9571
   F1 Macro   : 0.9074
   Class 0 — Prec: 0.9922  Rec: 0.9588  F1: 0.9752
   Class 1 — Prec: 0.7556  Rec: 0.9444  F1: 0.8395
   ⚠️  Class 1 recall 0.9444 below 95% target

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9922    0.9588    0.9752       534
           1     0.7556    0.9444    0.8395        72

    accuracy                         0.9571       606
   macro avg     0.8739    0.9516    0.9074       606
weighted avg     0.9641    0.9571    0.9591       606


🔧 LR=0.0005  |  batch_size=32

Loading weights:   0%|          | 0/198 [00:00<?, ?it/s]

DebertaV2ForSequenceClassification LOAD REPORT from: microsoft/mdeberta-v3-base
Key                                        | Status     |
-------------------------------------------+------------+-
mask_predictions.dense.weight              | UNEXPECTED |
mask_predictions.LayerNorm.weight          | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.bias      | UNEXPECTED |
mask_predictions.dense.bias                | UNEXPECTED |
mask_predictions.classifier.bias           | UNEXPECTED |
lm_predictions.lm_head.bias                | UNEXPECTED |
mask_predictions.classifier.weight         | UNEXPECTED |
lm_predictions.lm_head.dense.weight        | UNEXPECTED |
lm_predictions.lm_head.dense.bias          | UNEXPECTED |
mask_predictions.LayerNorm.bias            | UNEXPECTED |
deberta.embeddings.word_embeddings._weight | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.weight    | UNEXPECTED |
pooler.dense.weight                        | MISSING    |
pooler.dense.bias                          | MISSING    |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 591,362 || all params: 279,402,244 || trainable%: 0.2117

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 2, 'bos_token_id': 1}.

   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(7.45808383233533)]
🚀 Training...

⏸️  Recall hasn't improved for 2 evals. Best: 0.9444
   ✅ Training done — loss: 0.1530

📊 Test Set Results:
   Accuracy   : 0.9835
   F1 Macro   : 0.9591
   Class 0 — Prec: 0.9852  Rec: 0.9963  F1: 0.9907
   Class 1 — Prec: 0.9697  Rec: 0.8889  F1: 0.9275
   ⚠️  Class 1 recall 0.8889 below 95% target

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9852    0.9963    0.9907       534
           1     0.9697    0.8889    0.9275        72

    accuracy                         0.9835       606
   macro avg     0.9774    0.9426    0.9591       606
weighted avg     0.9833    0.9835    0.9832       606


🔧 LR=0.0005  |  batch_size=64

Loading weights:   0%|          | 0/198 [00:00<?, ?it/s]

DebertaV2ForSequenceClassification LOAD REPORT from: microsoft/mdeberta-v3-base
Key                                        | Status     |
-------------------------------------------+------------+-
mask_predictions.dense.weight              | UNEXPECTED |
mask_predictions.LayerNorm.weight          | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.bias      | UNEXPECTED |
mask_predictions.dense.bias                | UNEXPECTED |
mask_predictions.classifier.bias           | UNEXPECTED |
lm_predictions.lm_head.bias                | UNEXPECTED |
mask_predictions.classifier.weight         | UNEXPECTED |
lm_predictions.lm_head.dense.weight        | UNEXPECTED |
lm_predictions.lm_head.dense.bias          | UNEXPECTED |
mask_predictions.LayerNorm.bias            | UNEXPECTED |
deberta.embeddings.word_embeddings._weight | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.weight    | UNEXPECTED |
pooler.dense.weight                        | MISSING    |
pooler.dense.bias                          | MISSING    |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 591,362 || all params: 279,402,244 || trainable%: 0.2117

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 2, 'bos_token_id': 1}.

   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(7.45808383233533)]
🚀 Training...

⏸️  Recall hasn't improved for 2 evals. Best: 0.9167

⏸️  Recall hasn't improved for 2 evals. Best: 0.9167
   ✅ Training done — loss: 0.1660

📊 Test Set Results:
   Accuracy   : 0.9752
   F1 Macro   : 0.9405
   Class 0 — Prec: 0.9850  Rec: 0.9869  F1: 0.9860
   Class 1 — Prec: 0.9014  Rec: 0.8889  F1: 0.8951
   ⚠️  Class 1 recall 0.8889 below 95% target

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9850    0.9869    0.9860       534
           1     0.9014    0.8889    0.8951        72

    accuracy                         0.9752       606
   macro avg     0.9432    0.9379    0.9405       606
weighted avg     0.9751    0.9752    0.9752       606


🔧 LR=0.0007  |  batch_size=32

Loading weights:   0%|          | 0/198 [00:00<?, ?it/s]

DebertaV2ForSequenceClassification LOAD REPORT from: microsoft/mdeberta-v3-base
Key                                        | Status     |
-------------------------------------------+------------+-
mask_predictions.dense.weight              | UNEXPECTED |
mask_predictions.LayerNorm.weight          | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.bias      | UNEXPECTED |
mask_predictions.dense.bias                | UNEXPECTED |
mask_predictions.classifier.bias           | UNEXPECTED |
lm_predictions.lm_head.bias                | UNEXPECTED |
mask_predictions.classifier.weight         | UNEXPECTED |
lm_predictions.lm_head.dense.weight        | UNEXPECTED |
lm_predictions.lm_head.dense.bias          | UNEXPECTED |
mask_predictions.LayerNorm.bias            | UNEXPECTED |
deberta.embeddings.word_embeddings._weight | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.weight    | UNEXPECTED |
pooler.dense.weight                        | MISSING    |
pooler.dense.bias                          | MISSING    |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 591,362 || all params: 279,402,244 || trainable%: 0.2117

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 2, 'bos_token_id': 1}.

   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(7.45808383233533)]
🚀 Training...

⏸️  Recall hasn't improved for 2 evals. Best: 0.9444

⏸️  Recall hasn't improved for 2 evals. Best: 0.9444

⏸️  Recall hasn't improved for 2 evals. Best: 0.9444
   ✅ Training done — loss: 0.1513

📊 Test Set Results:
   Accuracy   : 0.9637
   F1 Macro   : 0.9182
   Class 0 — Prec: 0.9885  Rec: 0.9700  F1: 0.9792
   Class 1 — Prec: 0.8049  Rec: 0.9167  F1: 0.8571
   ⚠️  Class 1 recall 0.9167 below 95% target

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9885    0.9700    0.9792       534
           1     0.8049    0.9167    0.8571        72

    accuracy                         0.9637       606
   macro avg     0.8967    0.9434    0.9182       606
weighted avg     0.9667    0.9637    0.9647       606


🔧 LR=0.0007  |  batch_size=64

Loading weights:   0%|          | 0/198 [00:00<?, ?it/s]

DebertaV2ForSequenceClassification LOAD REPORT from: microsoft/mdeberta-v3-base
Key                                        | Status     |
-------------------------------------------+------------+-
mask_predictions.dense.weight              | UNEXPECTED |
mask_predictions.LayerNorm.weight          | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.bias      | UNEXPECTED |
mask_predictions.dense.bias                | UNEXPECTED |
mask_predictions.classifier.bias           | UNEXPECTED |
lm_predictions.lm_head.bias                | UNEXPECTED |
mask_predictions.classifier.weight         | UNEXPECTED |
lm_predictions.lm_head.dense.weight        | UNEXPECTED |
lm_predictions.lm_head.dense.bias          | UNEXPECTED |
mask_predictions.LayerNorm.bias            | UNEXPECTED |
deberta.embeddings.word_embeddings._weight | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.weight    | UNEXPECTED |
pooler.dense.weight                        | MISSING    |
pooler.dense.bias                          | MISSING    |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 591,362 || all params: 279,402,244 || trainable%: 0.2117

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 2, 'bos_token_id': 1}.

   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(7.45808383233533)]
🚀 Training...

⏸️  Recall hasn't improved for 2 evals. Best: 0.9028
   ✅ Training done — loss: 0.1530

📊 Test Set Results:
   Accuracy   : 0.9752
   F1 Macro   : 0.9405
   Class 0 — Prec: 0.9850  Rec: 0.9869  F1: 0.9860
   Class 1 — Prec: 0.9014  Rec: 0.8889  F1: 0.8951
   ⚠️  Class 1 recall 0.8889 below 95% target

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9850    0.9869    0.9860       534
           1     0.9014    0.8889    0.8951        72

    accuracy                         0.9752       606
   macro avg     0.9432    0.9379    0.9405       606
weighted avg     0.9751    0.9752    0.9752       606


🔧 Attempting threshold adjustment to reach 95% recall...

============================================================
🎯 THRESHOLD OPTIMIZATION FOR 95% RECALL
============================================================

📊 Optimal threshold : 0.3520
   Accuracy          : 0.8993
   Class 0 — Prec: 0.9937  Rec: 0.8914  F1: 0.9398
   Class 1 — Prec: 0.5433  Rec: 0.9583  F1: 0.6935  ✅ MEETS TARGET!

   Confusion Matrix:
[[476  58]
 [  3  69]]
   TN:476  FP:58  FN:3  TP:69

              precision    recall  f1-score   support

           0     0.9937    0.8914    0.9398       534
           1     0.5433    0.9583    0.6935        72

    accuracy                         0.8993       606
   macro avg     0.7685    0.9249    0.8166       606
weighted avg     0.9402    0.8993    0.9105       606


============================================================
📊 GRID SEARCH SUMMARY — HINDI / MDEBERTA
============================================================
    LR  Batch Size Accuracy F1 Macro Recall (C1) F1 (C1) Precision (C1)
0.0003          32   0.9785   0.9485      0.9028  0.9091         0.9155
0.0003          64   0.9571   0.9074      0.9583  0.6935         0.5433
0.0005          32   0.9835   0.9591      0.8889  0.9275         0.9697
0.0005          64   0.9752   0.9405      0.8889  0.8951         0.9014
0.0007          32   0.9637   0.9182      0.9167  0.8571         0.8049
0.0007          64   0.9752   0.9405      0.8889  0.8951         0.9014

💾 Results saved to lora_results_Hindi_mdeberta.csv

============================================================
🏅 BEST RUN — LR=0.0003, batch_size=64
============================================================
   Accuracy  : 0.9571
   F1 Macro  : 0.9074
   Class 0 — Prec:0.9922  Rec:0.9588  F1:0.9752
   Class 1 — Prec:0.5433  Rec:0.9583  F1:0.6935
   Applied threshold : 0.3520
✅ Best model saved to: /content/drive/MyDrive/Models/Hindi_mdeberta_lora/Hindi_mdeberta_best

config.json:   0%|          | 0.00/507 [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/5.65M [00:00<?, ?B/s]

🔄 Tokenizing datasets...

Map:   0%|          | 0/2825 [00:00<?, ? examples/s]

Map:   0%|          | 0/606 [00:00<?, ? examples/s]

Map:   0%|          | 0/606 [00:00<?, ? examples/s]

   ✅ Train : 2,825   Val : 606   Test : 606

############################################################
# LANGUAGE : Hindi  |  MODEL : indicbert
# ai4bharat/indic-bert
# Batch sizes    : [32, 64]
# Learning rates : [0.0003, 0.0005, 0.0007]
# Focal gamma    : 2.5  |  Minority boost: 1.0×
# Early stop on Class-1 recall >= 95%
############################################################

🔧 LR=0.0003  |  batch_size=32

pytorch_model.bin:   0%|          | 0.00/135M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/25 [00:00<?, ?it/s]

AlbertForSequenceClassification LOAD REPORT from: ai4bharat/indic-bert
Key                              | Status     |
---------------------------------+------------+-
predictions.LayerNorm.weight     | UNEXPECTED |
predictions.LayerNorm.bias       | UNEXPECTED |
predictions.dense.bias           | UNEXPECTED |
predictions.decoder.bias         | UNEXPECTED |
predictions.dense.weight         | UNEXPECTED |
sop_classifier.classifier.bias   | UNEXPECTED |
sop_classifier.classifier.weight | UNEXPECTED |
predictions.decoder.weight       | UNEXPECTED |
predictions.bias                 | UNEXPECTED |
classifier.weight                | MISSING    |
classifier.bias                  | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 99,842 || all params: 33,544,964 || trainable%: 0.2976

model.safetensors:   0%|          | 0.00/135M [00:00<?, ?B/s]

   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(7.45808383233533)]
🚀 Training...

⏸️  Recall hasn't improved for 2 evals. Best: 0.9028

⏸️  Recall hasn't improved for 2 evals. Best: 0.9028
   ✅ Training done — loss: 0.2846

📊 Test Set Results:
   Accuracy   : 0.9092
   F1 Macro   : 0.8291
   Class 0 — Prec: 0.9918  Rec: 0.9045  F1: 0.9461
   Class 1 — Prec: 0.5714  Rec: 0.9444  F1: 0.7120
   ⚠️  Class 1 recall 0.9444 below 95% target

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9918    0.9045    0.9461       534
           1     0.5714    0.9444    0.7120        72

    accuracy                         0.9092       606
   macro avg     0.7816    0.9245    0.8291       606
weighted avg     0.9418    0.9092    0.9183       606


🔧 LR=0.0003  |  batch_size=64

Loading weights:   0%|          | 0/25 [00:00<?, ?it/s]

AlbertForSequenceClassification LOAD REPORT from: ai4bharat/indic-bert
Key                              | Status     |
---------------------------------+------------+-
predictions.LayerNorm.weight     | UNEXPECTED |
predictions.LayerNorm.bias       | UNEXPECTED |
predictions.dense.bias           | UNEXPECTED |
predictions.decoder.bias         | UNEXPECTED |
predictions.dense.weight         | UNEXPECTED |
sop_classifier.classifier.bias   | UNEXPECTED |
sop_classifier.classifier.weight | UNEXPECTED |
predictions.decoder.weight       | UNEXPECTED |
predictions.bias                 | UNEXPECTED |
classifier.weight                | MISSING    |
classifier.bias                  | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 99,842 || all params: 33,544,964 || trainable%: 0.2976
   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(7.45808383233533)]
🚀 Training...

🎯 Target recall 95.00% achieved! Current: 0.9722
   Stopping training early...
   ✅ Training done — loss: 0.3954

📊 Test Set Results:
   Accuracy   : 0.9323
   F1 Macro   : 0.8644
   Class 0 — Prec: 0.9920  Rec: 0.9307  F1: 0.9604
   Class 1 — Prec: 0.6476  Rec: 0.9444  F1: 0.7684
   ⚠️  Class 1 recall 0.9444 below 95% target

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9920    0.9307    0.9604       534
           1     0.6476    0.9444    0.7684        72

    accuracy                         0.9323       606
   macro avg     0.8198    0.9376    0.8644       606
weighted avg     0.9511    0.9323    0.9376       606


🔧 LR=0.0005  |  batch_size=32

Loading weights:   0%|          | 0/25 [00:00<?, ?it/s]

AlbertForSequenceClassification LOAD REPORT from: ai4bharat/indic-bert
Key                              | Status     |
---------------------------------+------------+-
predictions.LayerNorm.weight     | UNEXPECTED |
predictions.LayerNorm.bias       | UNEXPECTED |
predictions.dense.bias           | UNEXPECTED |
predictions.decoder.bias         | UNEXPECTED |
predictions.dense.weight         | UNEXPECTED |
sop_classifier.classifier.bias   | UNEXPECTED |
sop_classifier.classifier.weight | UNEXPECTED |
predictions.decoder.weight       | UNEXPECTED |
predictions.bias                 | UNEXPECTED |
classifier.weight                | MISSING    |
classifier.bias                  | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 99,842 || all params: 33,544,964 || trainable%: 0.2976
   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(7.45808383233533)]
🚀 Training...

🎯 Target recall 95.00% achieved! Current: 0.9583
   Stopping training early...
   ✅ Training done — loss: 0.5509

📊 Test Set Results:
   Accuracy   : 0.7871
   F1 Macro   : 0.6934
   Class 0 — Prec: 0.9975  Rec: 0.7603  F1: 0.8629
   Class 1 — Prec: 0.3568  Rec: 0.9861  F1: 0.5240
   ✅ Class 1 recall 0.9861 meets target!

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9975    0.7603    0.8629       534
           1     0.3568    0.9861    0.5240        72

    accuracy                         0.7871       606
   macro avg     0.6772    0.8732    0.6934       606
weighted avg     0.9214    0.7871    0.8226       606


🔧 LR=0.0005  |  batch_size=64

Loading weights:   0%|          | 0/25 [00:00<?, ?it/s]

AlbertForSequenceClassification LOAD REPORT from: ai4bharat/indic-bert
Key                              | Status     |
---------------------------------+------------+-
predictions.LayerNorm.weight     | UNEXPECTED |
predictions.LayerNorm.bias       | UNEXPECTED |
predictions.dense.bias           | UNEXPECTED |
predictions.decoder.bias         | UNEXPECTED |
predictions.dense.weight         | UNEXPECTED |
sop_classifier.classifier.bias   | UNEXPECTED |
sop_classifier.classifier.weight | UNEXPECTED |
predictions.decoder.weight       | UNEXPECTED |
predictions.bias                 | UNEXPECTED |
classifier.weight                | MISSING    |
classifier.bias                  | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 99,842 || all params: 33,544,964 || trainable%: 0.2976
   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(7.45808383233533)]
🚀 Training...

🎯 Target recall 95.00% achieved! Current: 0.9722
   Stopping training early...
   ✅ Training done — loss: 0.5874

📊 Test Set Results:
   Accuracy   : 0.7640
   F1 Macro   : 0.6720
   Class 0 — Prec: 0.9975  Rec: 0.7341  F1: 0.8457
   Class 1 — Prec: 0.3333  Rec: 0.9861  F1: 0.4982
   ✅ Class 1 recall 0.9861 meets target!

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9975    0.7341    0.8457       534
           1     0.3333    0.9861    0.4982        72

    accuracy                         0.7640       606
   macro avg     0.6654    0.8601    0.6720       606
weighted avg     0.9185    0.7640    0.8045       606


🔧 LR=0.0007  |  batch_size=32

Loading weights:   0%|          | 0/25 [00:00<?, ?it/s]

AlbertForSequenceClassification LOAD REPORT from: ai4bharat/indic-bert
Key                              | Status     |
---------------------------------+------------+-
predictions.LayerNorm.weight     | UNEXPECTED |
predictions.LayerNorm.bias       | UNEXPECTED |
predictions.dense.bias           | UNEXPECTED |
predictions.decoder.bias         | UNEXPECTED |
predictions.dense.weight         | UNEXPECTED |
sop_classifier.classifier.bias   | UNEXPECTED |
sop_classifier.classifier.weight | UNEXPECTED |
predictions.decoder.weight       | UNEXPECTED |
predictions.bias                 | UNEXPECTED |
classifier.weight                | MISSING    |
classifier.bias                  | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 99,842 || all params: 33,544,964 || trainable%: 0.2976
   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(7.45808383233533)]
🚀 Training...

🎯 Target recall 95.00% achieved! Current: 1.0000
   Stopping training early...
   ✅ Training done — loss: 0.6375

📊 Test Set Results:
   Accuracy   : 0.1188
   F1 Macro   : 0.1062
   Class 0 — Prec: 0.0000  Rec: 0.0000  F1: 0.0000
   Class 1 — Prec: 0.1188  Rec: 1.0000  F1: 0.2124
   ✅ Class 1 recall 1.0000 meets target!

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.0000    0.0000    0.0000       534
           1     0.1188    1.0000    0.2124        72

    accuracy                         0.1188       606
   macro avg     0.0594    0.5000    0.1062       606
weighted avg     0.0141    0.1188    0.0252       606


🔧 LR=0.0007  |  batch_size=64

Loading weights:   0%|          | 0/25 [00:00<?, ?it/s]

AlbertForSequenceClassification LOAD REPORT from: ai4bharat/indic-bert
Key                              | Status     |
---------------------------------+------------+-
predictions.LayerNorm.weight     | UNEXPECTED |
predictions.LayerNorm.bias       | UNEXPECTED |
predictions.dense.bias           | UNEXPECTED |
predictions.decoder.bias         | UNEXPECTED |
predictions.dense.weight         | UNEXPECTED |
sop_classifier.classifier.bias   | UNEXPECTED |
sop_classifier.classifier.weight | UNEXPECTED |
predictions.decoder.weight       | UNEXPECTED |
predictions.bias                 | UNEXPECTED |
classifier.weight                | MISSING    |
classifier.bias                  | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 99,842 || all params: 33,544,964 || trainable%: 0.2976
   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(7.45808383233533)]
🚀 Training...

🎯 Target recall 95.00% achieved! Current: 0.9583
   Stopping training early...
   ✅ Training done — loss: 0.5652

📊 Test Set Results:
   Accuracy   : 0.6848
   F1 Macro   : 0.6046
   Class 0 — Prec: 0.9971  Rec: 0.6442  F1: 0.7827
   Class 1 — Prec: 0.2720  Rec: 0.9861  F1: 0.4264
   ✅ Class 1 recall 0.9861 meets target!

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9971    0.6442    0.7827       534
           1     0.2720    0.9861    0.4264        72

    accuracy                         0.6848       606
   macro avg     0.6346    0.8152    0.6046       606
weighted avg     0.9110    0.6848    0.7404       606


============================================================
📊 GRID SEARCH SUMMARY — HINDI / INDICBERT
============================================================
    LR  Batch Size Accuracy F1 Macro Recall (C1) F1 (C1) Precision (C1)
0.0003          32   0.9092   0.8291      0.9444  0.7120         0.5714
0.0003          64   0.9323   0.8644      0.9444  0.7684         0.6476
0.0005          32   0.7871   0.6934      0.9861  0.5240         0.3568
0.0005          64   0.7640   0.6720      0.9861  0.4982         0.3333
0.0007          32   0.1188   0.1062      1.0000  0.2124         0.1188
0.0007          64   0.6848   0.6046      0.9861  0.4264         0.2720

💾 Results saved to lora_results_Hindi_indicbert.csv

============================================================
🏅 BEST RUN — LR=0.0007, batch_size=32
============================================================
   Accuracy  : 0.1188
   F1 Macro  : 0.1062
   Class 0 — Prec:0.0000  Rec:0.0000  F1:0.0000
   Class 1 — Prec:0.1188  Rec:1.0000  F1:0.2124
✅ Best model saved to: /content/drive/MyDrive/Models/Hindi_indicbert_lora/Hindi_indicbert_best

config.json:   0%|          | 0.00/615 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

🔄 Tokenizing datasets...

Map:   0%|          | 0/2825 [00:00<?, ? examples/s]

Map:   0%|          | 0/606 [00:00<?, ? examples/s]

Map:   0%|          | 0/606 [00:00<?, ? examples/s]

   ✅ Train : 2,825   Val : 606   Test : 606

############################################################
# LANGUAGE : Hindi  |  MODEL : xlm-roberta
# xlm-roberta-base
# Batch sizes    : [32, 64]
# Learning rates : [0.0003, 0.0005, 0.0007]
# Focal gamma    : 2.5  |  Minority boost: 1.0×
# Early stop on Class-1 recall >= 95%
############################################################

🔧 LR=0.0003  |  batch_size=32

model.safetensors:   0%|          | 0.00/1.12G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForSequenceClassification LOAD REPORT from: xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
classifier.out_proj.bias    | MISSING    |
classifier.dense.weight     | MISSING    |
classifier.dense.bias       | MISSING    |
classifier.out_proj.weight  | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 1,181,954 || all params: 279,227,140 || trainable%: 0.4233
   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(7.45808383233533)]
🚀 Training...

🎯 Target recall 95.00% achieved! Current: 0.9583
   Stopping training early...
   ✅ Training done — loss: 0.2323

📊 Test Set Results:
   Accuracy   : 0.9818
   F1 Macro   : 0.9569
   Class 0 — Prec: 0.9906  Rec: 0.9888  F1: 0.9897
   Class 1 — Prec: 0.9178  Rec: 0.9306  F1: 0.9241
   ⚠️  Class 1 recall 0.9306 below 95% target

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9906    0.9888    0.9897       534
           1     0.9178    0.9306    0.9241        72

    accuracy                         0.9818       606
   macro avg     0.9542    0.9597    0.9569       606
weighted avg     0.9820    0.9818    0.9819       606


🔧 LR=0.0003  |  batch_size=64

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForSequenceClassification LOAD REPORT from: xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
classifier.out_proj.bias    | MISSING    |
classifier.dense.weight     | MISSING    |
classifier.dense.bias       | MISSING    |
classifier.out_proj.weight  | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 1,181,954 || all params: 279,227,140 || trainable%: 0.4233
   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(7.45808383233533)]
🚀 Training...

🎯 Target recall 95.00% achieved! Current: 0.9861
   Stopping training early...
   ✅ Training done — loss: 0.4325

📊 Test Set Results:
   Accuracy   : 0.8053
   F1 Macro   : 0.7111
   Class 0 — Prec: 0.9976  Rec: 0.7809  F1: 0.8761
   Class 1 — Prec: 0.3777  Rec: 0.9861  F1: 0.5462
   ✅ Class 1 recall 0.9861 meets target!

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9976    0.7809    0.8761       534
           1     0.3777    0.9861    0.5462        72

    accuracy                         0.8053       606
   macro avg     0.6876    0.8835    0.7111       606
weighted avg     0.9240    0.8053    0.8369       606


🔧 LR=0.0005  |  batch_size=32

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForSequenceClassification LOAD REPORT from: xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
classifier.out_proj.bias    | MISSING    |
classifier.dense.weight     | MISSING    |
classifier.dense.bias       | MISSING    |
classifier.out_proj.weight  | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 1,181,954 || all params: 279,227,140 || trainable%: 0.4233
   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(7.45808383233533)]
🚀 Training...

🎯 Target recall 95.00% achieved! Current: 0.9722
   Stopping training early...
   ✅ Training done — loss: 0.2341

📊 Test Set Results:
   Accuracy   : 0.9884
   F1 Macro   : 0.9726
   Class 0 — Prec: 0.9944  Rec: 0.9925  F1: 0.9934
   Class 1 — Prec: 0.9452  Rec: 0.9583  F1: 0.9517
   ✅ Class 1 recall 0.9583 meets target!

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9944    0.9925    0.9934       534
           1     0.9452    0.9583    0.9517        72

    accuracy                         0.9884       606
   macro avg     0.9698    0.9754    0.9726       606
weighted avg     0.9885    0.9884    0.9885       606


🔧 LR=0.0005  |  batch_size=64

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForSequenceClassification LOAD REPORT from: xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
classifier.out_proj.bias    | MISSING    |
classifier.dense.weight     | MISSING    |
classifier.dense.bias       | MISSING    |
classifier.out_proj.weight  | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 1,181,954 || all params: 279,227,140 || trainable%: 0.4233
   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(7.45808383233533)]
🚀 Training...

🎯 Target recall 95.00% achieved! Current: 0.9722
   Stopping training early...
   ✅ Training done — loss: 0.4226

📊 Test Set Results:
   Accuracy   : 0.8762
   F1 Macro   : 0.7864
   Class 0 — Prec: 0.9935  Rec: 0.8652  F1: 0.9249
   Class 1 — Prec: 0.4894  Rec: 0.9583  F1: 0.6479
   ✅ Class 1 recall 0.9583 meets target!

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9935    0.8652    0.9249       534
           1     0.4894    0.9583    0.6479        72

    accuracy                         0.8762       606
   macro avg     0.7415    0.9118    0.7864       606
weighted avg     0.9336    0.8762    0.8920       606


🔧 LR=0.0007  |  batch_size=32

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForSequenceClassification LOAD REPORT from: xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
classifier.out_proj.bias    | MISSING    |
classifier.dense.weight     | MISSING    |
classifier.dense.bias       | MISSING    |
classifier.out_proj.weight  | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 1,181,954 || all params: 279,227,140 || trainable%: 0.4233
   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(7.45808383233533)]
🚀 Training...

🎯 Target recall 95.00% achieved! Current: 0.9722
   Stopping training early...
   ✅ Training done — loss: 0.2111

📊 Test Set Results:
   Accuracy   : 0.9851
   F1 Macro   : 0.9652
   Class 0 — Prec: 0.9944  Rec: 0.9888  F1: 0.9915
   Class 1 — Prec: 0.9200  Rec: 0.9583  F1: 0.9388
   ✅ Class 1 recall 0.9583 meets target!

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9944    0.9888    0.9915       534
           1     0.9200    0.9583    0.9388        72

    accuracy                         0.9851       606
   macro avg     0.9572    0.9735    0.9652       606
weighted avg     0.9855    0.9851    0.9853       606


🔧 LR=0.0007  |  batch_size=64

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForSequenceClassification LOAD REPORT from: xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
classifier.out_proj.bias    | MISSING    |
classifier.dense.weight     | MISSING    |
classifier.dense.bias       | MISSING    |
classifier.out_proj.weight  | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 1,181,954 || all params: 279,227,140 || trainable%: 0.4233
   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(7.45808383233533)]
🚀 Training...

🎯 Target recall 95.00% achieved! Current: 0.9861
   Stopping training early...
   ✅ Training done — loss: 0.4161

📊 Test Set Results:
   Accuracy   : 0.9307
   F1 Macro   : 0.8642
   Class 0 — Prec: 0.9960  Rec: 0.9251  F1: 0.9592
   Class 1 — Prec: 0.6364  Rec: 0.9722  F1: 0.7692
   ✅ Class 1 recall 0.9722 meets target!

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9960    0.9251    0.9592       534
           1     0.6364    0.9722    0.7692        72

    accuracy                         0.9307       606
   macro avg     0.8162    0.9487    0.8642       606
weighted avg     0.9532    0.9307    0.9366       606


============================================================
📊 GRID SEARCH SUMMARY — HINDI / XLM-ROBERTA
============================================================
    LR  Batch Size Accuracy F1 Macro Recall (C1) F1 (C1) Precision (C1)
0.0003          32   0.9818   0.9569      0.9306  0.9241         0.9178
0.0003          64   0.8053   0.7111      0.9861  0.5462         0.3777
0.0005          32   0.9884   0.9726      0.9583  0.9517         0.9452
0.0005          64   0.8762   0.7864      0.9583  0.6479         0.4894
0.0007          32   0.9851   0.9652      0.9583  0.9388         0.9200
0.0007          64   0.9307   0.8642      0.9722  0.7692         0.6364

💾 Results saved to lora_results_Hindi_xlm-roberta.csv

============================================================
🏅 BEST RUN — LR=0.0003, batch_size=64
============================================================
   Accuracy  : 0.8053
   F1 Macro  : 0.7111
   Class 0 — Prec:0.9976  Rec:0.7809  F1:0.8761
   Class 1 — Prec:0.3777  Rec:0.9861  F1:0.5462
✅ Best model saved to: /content/drive/MyDrive/Models/Hindi_xlm-roberta_lora/Hindi_xlm-roberta_best

============================================================
  LOADING DATASET FOR LANGUAGE: Tamil
============================================================

============================================================
📂 DATASET LOADING WITH STRATIFICATION
============================================================

📊 Original dataset : 4,890 rows
   Class 0: 4,076  (83.4%)
   Class 1: 814  (16.6%)

   ⚠️  Imbalance ratio: 5.01:1  → Focal Loss will help

   TRAIN (3,422):
      Class 0: 2,852  (83.3%)
      Class 1: 570  (16.7%)

   VAL (734):
      Class 0: 612  (83.4%)
      Class 1: 122  (16.6%)

   TEST (734):
      Class 0: 612  (83.4%)
      Class 1: 122  (16.6%)

📊 Class weights (minority boost=1.0×): [np.float64(1.0), np.float64(5.003508771929824)]
💾 Splits saved to /content/drive/MyDrive/Models/splits_tamil/

🔄 Tokenizing datasets...

Map:   0%|          | 0/3422 [00:00<?, ? examples/s]

Map:   0%|          | 0/734 [00:00<?, ? examples/s]

Map:   0%|          | 0/734 [00:00<?, ? examples/s]

   ✅ Train : 3,422   Val : 734   Test : 734

############################################################
# LANGUAGE : Tamil  |  MODEL : mdeberta
# microsoft/mdeberta-v3-base
# Batch sizes    : [32, 64]
# Learning rates : [0.0003, 0.0005, 0.0007]
# Focal gamma    : 2.5  |  Minority boost: 1.0×
# Early stop on Class-1 recall >= 95%
############################################################

🔧 LR=0.0003  |  batch_size=32

Loading weights:   0%|          | 0/198 [00:00<?, ?it/s]

DebertaV2ForSequenceClassification LOAD REPORT from: microsoft/mdeberta-v3-base
Key                                        | Status     |
-------------------------------------------+------------+-
mask_predictions.dense.weight              | UNEXPECTED |
mask_predictions.LayerNorm.weight          | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.bias      | UNEXPECTED |
mask_predictions.dense.bias                | UNEXPECTED |
mask_predictions.classifier.bias           | UNEXPECTED |
lm_predictions.lm_head.bias                | UNEXPECTED |
mask_predictions.classifier.weight         | UNEXPECTED |
lm_predictions.lm_head.dense.weight        | UNEXPECTED |
lm_predictions.lm_head.dense.bias          | UNEXPECTED |
mask_predictions.LayerNorm.bias            | UNEXPECTED |
deberta.embeddings.word_embeddings._weight | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.weight    | UNEXPECTED |
pooler.dense.weight                        | MISSING    |
pooler.dense.bias                          | MISSING    |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 591,362 || all params: 279,402,244 || trainable%: 0.2117

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 2, 'bos_token_id': 1}.

   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(5.003508771929824)]
🚀 Training...

   ✅ Training done — loss: 0.1672

📊 Test Set Results:
   Accuracy   : 0.9728
   F1 Macro   : 0.9518
   Class 0 — Prec: 0.9884  Rec: 0.9788  F1: 0.9836
   Class 1 — Prec: 0.8984  Rec: 0.9426  F1: 0.9200
   ⚠️  Class 1 recall 0.9426 below 95% target

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9884    0.9788    0.9836       612
           1     0.8984    0.9426    0.9200       122

    accuracy                         0.9728       734
   macro avg     0.9434    0.9607    0.9518       734
weighted avg     0.9735    0.9728    0.9730       734


🔧 LR=0.0003  |  batch_size=64

Loading weights:   0%|          | 0/198 [00:00<?, ?it/s]

DebertaV2ForSequenceClassification LOAD REPORT from: microsoft/mdeberta-v3-base
Key                                        | Status     |
-------------------------------------------+------------+-
mask_predictions.dense.weight              | UNEXPECTED |
mask_predictions.LayerNorm.weight          | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.bias      | UNEXPECTED |
mask_predictions.dense.bias                | UNEXPECTED |
mask_predictions.classifier.bias           | UNEXPECTED |
lm_predictions.lm_head.bias                | UNEXPECTED |
mask_predictions.classifier.weight         | UNEXPECTED |
lm_predictions.lm_head.dense.weight        | UNEXPECTED |
lm_predictions.lm_head.dense.bias          | UNEXPECTED |
mask_predictions.LayerNorm.bias            | UNEXPECTED |
deberta.embeddings.word_embeddings._weight | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.weight    | UNEXPECTED |
pooler.dense.weight                        | MISSING    |
pooler.dense.bias                          | MISSING    |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 591,362 || all params: 279,402,244 || trainable%: 0.2117

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 2, 'bos_token_id': 1}.

   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(5.003508771929824)]
🚀 Training...

⏸️  Recall hasn't improved for 2 evals. Best: 0.8934
   ✅ Training done — loss: 0.2052

📊 Test Set Results:
   Accuracy   : 0.9305
   F1 Macro   : 0.8853
   Class 0 — Prec: 0.9811  Rec: 0.9346  F1: 0.9573
   Class 1 — Prec: 0.7351  Rec: 0.9098  F1: 0.8132
   ⚠️  Class 1 recall 0.9098 below 95% target

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9811    0.9346    0.9573       612
           1     0.7351    0.9098    0.8132       122

    accuracy                         0.9305       734
   macro avg     0.8581    0.9222    0.8853       734
weighted avg     0.9402    0.9305    0.9334       734


🔧 LR=0.0005  |  batch_size=32

Loading weights:   0%|          | 0/198 [00:00<?, ?it/s]

DebertaV2ForSequenceClassification LOAD REPORT from: microsoft/mdeberta-v3-base
Key                                        | Status     |
-------------------------------------------+------------+-
mask_predictions.dense.weight              | UNEXPECTED |
mask_predictions.LayerNorm.weight          | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.bias      | UNEXPECTED |
mask_predictions.dense.bias                | UNEXPECTED |
mask_predictions.classifier.bias           | UNEXPECTED |
lm_predictions.lm_head.bias                | UNEXPECTED |
mask_predictions.classifier.weight         | UNEXPECTED |
lm_predictions.lm_head.dense.weight        | UNEXPECTED |
lm_predictions.lm_head.dense.bias          | UNEXPECTED |
mask_predictions.LayerNorm.bias            | UNEXPECTED |
deberta.embeddings.word_embeddings._weight | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.weight    | UNEXPECTED |
pooler.dense.weight                        | MISSING    |
pooler.dense.bias                          | MISSING    |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 591,362 || all params: 279,402,244 || trainable%: 0.2117

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 2, 'bos_token_id': 1}.

   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(5.003508771929824)]
🚀 Training...

   ✅ Training done — loss: 0.1546

📊 Test Set Results:
   Accuracy   : 0.9646
   F1 Macro   : 0.9389
   Class 0 — Prec: 0.9900  Rec: 0.9673  F1: 0.9785
   Class 1 — Prec: 0.8529  Rec: 0.9508  F1: 0.8992
   ✅ Class 1 recall 0.9508 meets target!

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9900    0.9673    0.9785       612
           1     0.8529    0.9508    0.8992       122

    accuracy                         0.9646       734
   macro avg     0.9215    0.9591    0.9389       734
weighted avg     0.9672    0.9646    0.9653       734


🔧 LR=0.0005  |  batch_size=64

Loading weights:   0%|          | 0/198 [00:00<?, ?it/s]

DebertaV2ForSequenceClassification LOAD REPORT from: microsoft/mdeberta-v3-base
Key                                        | Status     |
-------------------------------------------+------------+-
mask_predictions.dense.weight              | UNEXPECTED |
mask_predictions.LayerNorm.weight          | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.bias      | UNEXPECTED |
mask_predictions.dense.bias                | UNEXPECTED |
mask_predictions.classifier.bias           | UNEXPECTED |
lm_predictions.lm_head.bias                | UNEXPECTED |
mask_predictions.classifier.weight         | UNEXPECTED |
lm_predictions.lm_head.dense.weight        | UNEXPECTED |
lm_predictions.lm_head.dense.bias          | UNEXPECTED |
mask_predictions.LayerNorm.bias            | UNEXPECTED |
deberta.embeddings.word_embeddings._weight | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.weight    | UNEXPECTED |
pooler.dense.weight                        | MISSING    |
pooler.dense.bias                          | MISSING    |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 591,362 || all params: 279,402,244 || trainable%: 0.2117

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 2, 'bos_token_id': 1}.

   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(5.003508771929824)]
🚀 Training...

⏸️  Recall hasn't improved for 2 evals. Best: 0.9180

⏸️  Recall hasn't improved for 2 evals. Best: 0.9180

⏸️  Recall hasn't improved for 2 evals. Best: 0.9180
   ✅ Training done — loss: 0.1716

📊 Test Set Results:
   Accuracy   : 0.8025
   F1 Macro   : 0.7412
   Class 0 — Prec: 0.9875  Rec: 0.7729  F1: 0.8671
   Class 1 — Prec: 0.4549  Rec: 0.9508  F1: 0.6154
   ✅ Class 1 recall 0.9508 meets target!

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9875    0.7729    0.8671       612
           1     0.4549    0.9508    0.6154       122

    accuracy                         0.8025       734
   macro avg     0.7212    0.8618    0.7412       734
weighted avg     0.8990    0.8025    0.8253       734


🔧 LR=0.0007  |  batch_size=32

Loading weights:   0%|          | 0/198 [00:00<?, ?it/s]

DebertaV2ForSequenceClassification LOAD REPORT from: microsoft/mdeberta-v3-base
Key                                        | Status     |
-------------------------------------------+------------+-
mask_predictions.dense.weight              | UNEXPECTED |
mask_predictions.LayerNorm.weight          | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.bias      | UNEXPECTED |
mask_predictions.dense.bias                | UNEXPECTED |
mask_predictions.classifier.bias           | UNEXPECTED |
lm_predictions.lm_head.bias                | UNEXPECTED |
mask_predictions.classifier.weight         | UNEXPECTED |
lm_predictions.lm_head.dense.weight        | UNEXPECTED |
lm_predictions.lm_head.dense.bias          | UNEXPECTED |
mask_predictions.LayerNorm.bias            | UNEXPECTED |
deberta.embeddings.word_embeddings._weight | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.weight    | UNEXPECTED |
pooler.dense.weight                        | MISSING    |
pooler.dense.bias                          | MISSING    |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 591,362 || all params: 279,402,244 || trainable%: 0.2117

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 2, 'bos_token_id': 1}.

   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(5.003508771929824)]
🚀 Training...

   ✅ Training done — loss: 0.1382

📊 Test Set Results:
   Accuracy   : 0.9673
   F1 Macro   : 0.9432
   Class 0 — Prec: 0.9900  Rec: 0.9706  F1: 0.9802
   Class 1 — Prec: 0.8657  Rec: 0.9508  F1: 0.9062
   ✅ Class 1 recall 0.9508 meets target!

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9900    0.9706    0.9802       612
           1     0.8657    0.9508    0.9062       122

    accuracy                         0.9673       734
   macro avg     0.9278    0.9607    0.9432       734
weighted avg     0.9693    0.9673    0.9679       734


🔧 LR=0.0007  |  batch_size=64

Loading weights:   0%|          | 0/198 [00:00<?, ?it/s]

DebertaV2ForSequenceClassification LOAD REPORT from: microsoft/mdeberta-v3-base
Key                                        | Status     |
-------------------------------------------+------------+-
mask_predictions.dense.weight              | UNEXPECTED |
mask_predictions.LayerNorm.weight          | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.bias      | UNEXPECTED |
mask_predictions.dense.bias                | UNEXPECTED |
mask_predictions.classifier.bias           | UNEXPECTED |
lm_predictions.lm_head.bias                | UNEXPECTED |
mask_predictions.classifier.weight         | UNEXPECTED |
lm_predictions.lm_head.dense.weight        | UNEXPECTED |
lm_predictions.lm_head.dense.bias          | UNEXPECTED |
mask_predictions.LayerNorm.bias            | UNEXPECTED |
deberta.embeddings.word_embeddings._weight | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.weight    | UNEXPECTED |
pooler.dense.weight                        | MISSING    |
pooler.dense.bias                          | MISSING    |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 591,362 || all params: 279,402,244 || trainable%: 0.2117

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 2, 'bos_token_id': 1}.

   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(5.003508771929824)]
🚀 Training...

   ✅ Training done — loss: 0.1535

📊 Test Set Results:
   Accuracy   : 0.9632
   F1 Macro   : 0.9371
   Class 0 — Prec: 0.9916  Rec: 0.9641  F1: 0.9776
   Class 1 — Prec: 0.8417  Rec: 0.9590  F1: 0.8966
   ✅ Class 1 recall 0.9590 meets target!

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9916    0.9641    0.9776       612
           1     0.8417    0.9590    0.8966       122

    accuracy                         0.9632       734
   macro avg     0.9167    0.9615    0.9371       734
weighted avg     0.9667    0.9632    0.9642       734


============================================================
📊 GRID SEARCH SUMMARY — TAMIL / MDEBERTA
============================================================
    LR  Batch Size Accuracy F1 Macro Recall (C1) F1 (C1) Precision (C1)
0.0003          32   0.9728   0.9518      0.9426  0.9200         0.8984
0.0003          64   0.9305   0.8853      0.9098  0.8132         0.7351
0.0005          32   0.9646   0.9389      0.9508  0.8992         0.8529
0.0005          64   0.8025   0.7412      0.9508  0.6154         0.4549
0.0007          32   0.9673   0.9432      0.9508  0.9062         0.8657
0.0007          64   0.9632   0.9371      0.9590  0.8966         0.8417

💾 Results saved to lora_results_Tamil_mdeberta.csv

============================================================
🏅 BEST RUN — LR=0.0007, batch_size=64
============================================================
   Accuracy  : 0.9632
   F1 Macro  : 0.9371
   Class 0 — Prec:0.9916  Rec:0.9641  F1:0.9776
   Class 1 — Prec:0.8417  Rec:0.9590  F1:0.8966
✅ Best model saved to: /content/drive/MyDrive/Models/Tamil_mdeberta_lora/Tamil_mdeberta_best

🔄 Tokenizing datasets...

Map:   0%|          | 0/3422 [00:00<?, ? examples/s]

Map:   0%|          | 0/734 [00:00<?, ? examples/s]

Map:   0%|          | 0/734 [00:00<?, ? examples/s]

   ✅ Train : 3,422   Val : 734   Test : 734

############################################################
# LANGUAGE : Tamil  |  MODEL : indicbert
# ai4bharat/indic-bert
# Batch sizes    : [32, 64]
# Learning rates : [0.0003, 0.0005, 0.0007]
# Focal gamma    : 2.5  |  Minority boost: 1.0×
# Early stop on Class-1 recall >= 95%
############################################################

🔧 LR=0.0003  |  batch_size=32

Loading weights:   0%|          | 0/25 [00:00<?, ?it/s]

AlbertForSequenceClassification LOAD REPORT from: ai4bharat/indic-bert
Key                              | Status     |
---------------------------------+------------+-
predictions.LayerNorm.weight     | UNEXPECTED |
predictions.LayerNorm.bias       | UNEXPECTED |
predictions.dense.bias           | UNEXPECTED |
predictions.decoder.bias         | UNEXPECTED |
predictions.dense.weight         | UNEXPECTED |
sop_classifier.classifier.bias   | UNEXPECTED |
sop_classifier.classifier.weight | UNEXPECTED |
predictions.decoder.weight       | UNEXPECTED |
predictions.bias                 | UNEXPECTED |
classifier.weight                | MISSING    |
classifier.bias                  | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 99,842 || all params: 33,544,964 || trainable%: 0.2976
   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(5.003508771929824)]
🚀 Training...

⏸️  Recall hasn't improved for 2 evals. Best: 0.9098

⏸️  Recall hasn't improved for 2 evals. Best: 0.9098

⏸️  Recall hasn't improved for 2 evals. Best: 0.9098
   ✅ Training done — loss: 0.2086

📊 Test Set Results:
   Accuracy   : 0.6035
   F1 Macro   : 0.5624
   Class 0 — Prec: 0.9625  Rec: 0.5458  F1: 0.6966
   Class 1 — Prec: 0.2817  Rec: 0.8934  F1: 0.4283
   ⚠️  Class 1 recall 0.8934 below 95% target

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9625    0.5458    0.6966       612
           1     0.2817    0.8934    0.4283       122

    accuracy                         0.6035       734
   macro avg     0.6221    0.7196    0.5624       734
weighted avg     0.8494    0.6035    0.6520       734


🔧 LR=0.0003  |  batch_size=64

Loading weights:   0%|          | 0/25 [00:00<?, ?it/s]

AlbertForSequenceClassification LOAD REPORT from: ai4bharat/indic-bert
Key                              | Status     |
---------------------------------+------------+-
predictions.LayerNorm.weight     | UNEXPECTED |
predictions.LayerNorm.bias       | UNEXPECTED |
predictions.dense.bias           | UNEXPECTED |
predictions.decoder.bias         | UNEXPECTED |
predictions.dense.weight         | UNEXPECTED |
sop_classifier.classifier.bias   | UNEXPECTED |
sop_classifier.classifier.weight | UNEXPECTED |
predictions.decoder.weight       | UNEXPECTED |
predictions.bias                 | UNEXPECTED |
classifier.weight                | MISSING    |
classifier.bias                  | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 99,842 || all params: 33,544,964 || trainable%: 0.2976
   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(5.003508771929824)]
🚀 Training...

⏸️  Recall hasn't improved for 2 evals. Best: 0.8934

⏸️  Recall hasn't improved for 2 evals. Best: 0.8934

⏸️  Recall hasn't improved for 2 evals. Best: 0.8934
   ✅ Training done — loss: 0.2585

📊 Test Set Results:
   Accuracy   : 0.6104
   F1 Macro   : 0.5654
   Class 0 — Prec: 0.9553  Rec: 0.5588  F1: 0.7052
   Class 1 — Prec: 0.2819  Rec: 0.8689  F1: 0.4257
   ⚠️  Class 1 recall 0.8689 below 95% target

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9553    0.5588    0.7052       612
           1     0.2819    0.8689    0.4257       122

    accuracy                         0.6104       734
   macro avg     0.6186    0.7138    0.5654       734
weighted avg     0.8434    0.6104    0.6587       734


🔧 LR=0.0005  |  batch_size=32

Loading weights:   0%|          | 0/25 [00:00<?, ?it/s]

AlbertForSequenceClassification LOAD REPORT from: ai4bharat/indic-bert
Key                              | Status     |
---------------------------------+------------+-
predictions.LayerNorm.weight     | UNEXPECTED |
predictions.LayerNorm.bias       | UNEXPECTED |
predictions.dense.bias           | UNEXPECTED |
predictions.decoder.bias         | UNEXPECTED |
predictions.dense.weight         | UNEXPECTED |
sop_classifier.classifier.bias   | UNEXPECTED |
sop_classifier.classifier.weight | UNEXPECTED |
predictions.decoder.weight       | UNEXPECTED |
predictions.bias                 | UNEXPECTED |
classifier.weight                | MISSING    |
classifier.bias                  | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 99,842 || all params: 33,544,964 || trainable%: 0.2976
   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(5.003508771929824)]
🚀 Training...

⏸️  Recall hasn't improved for 2 evals. Best: 0.8852

⏸️  Recall hasn't improved for 2 evals. Best: 0.8852

⏸️  Recall hasn't improved for 2 evals. Best: 0.8852
   ✅ Training done — loss: 0.1753

📊 Test Set Results:
   Accuracy   : 0.8692
   F1 Macro   : 0.8073
   Class 0 — Prec: 0.9796  Rec: 0.8611  F1: 0.9165
   Class 1 — Prec: 0.5663  Rec: 0.9098  F1: 0.6981
   ⚠️  Class 1 recall 0.9098 below 95% target

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9796    0.8611    0.9165       612
           1     0.5663    0.9098    0.6981       122

    accuracy                         0.8692       734
   macro avg     0.7729    0.8855    0.8073       734
weighted avg     0.9109    0.8692    0.8802       734


🔧 LR=0.0005  |  batch_size=64

Loading weights:   0%|          | 0/25 [00:00<?, ?it/s]

AlbertForSequenceClassification LOAD REPORT from: ai4bharat/indic-bert
Key                              | Status     |
---------------------------------+------------+-
predictions.LayerNorm.weight     | UNEXPECTED |
predictions.LayerNorm.bias       | UNEXPECTED |
predictions.dense.bias           | UNEXPECTED |
predictions.decoder.bias         | UNEXPECTED |
predictions.dense.weight         | UNEXPECTED |
sop_classifier.classifier.bias   | UNEXPECTED |
sop_classifier.classifier.weight | UNEXPECTED |
predictions.decoder.weight       | UNEXPECTED |
predictions.bias                 | UNEXPECTED |
classifier.weight                | MISSING    |
classifier.bias                  | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 99,842 || all params: 33,544,964 || trainable%: 0.2976
   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(5.003508771929824)]
🚀 Training...

⏸️  Recall hasn't improved for 2 evals. Best: 0.9426

⏸️  Recall hasn't improved for 2 evals. Best: 0.9426

⏸️  Recall hasn't improved for 2 evals. Best: 0.9426
   ✅ Training done — loss: 0.2184

📊 Test Set Results:
   Accuracy   : 0.5681
   F1 Macro   : 0.5368
   Class 0 — Prec: 0.9712  Rec: 0.4967  F1: 0.6573
   Class 1 — Prec: 0.2684  Rec: 0.9262  F1: 0.4162
   ⚠️  Class 1 recall 0.9262 below 95% target

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9712    0.4967    0.6573       612
           1     0.2684    0.9262    0.4162       122

    accuracy                         0.5681       734
   macro avg     0.6198    0.7115    0.5368       734
weighted avg     0.8544    0.5681    0.6172       734


🔧 LR=0.0007  |  batch_size=32

Loading weights:   0%|          | 0/25 [00:00<?, ?it/s]

AlbertForSequenceClassification LOAD REPORT from: ai4bharat/indic-bert
Key                              | Status     |
---------------------------------+------------+-
predictions.LayerNorm.weight     | UNEXPECTED |
predictions.LayerNorm.bias       | UNEXPECTED |
predictions.dense.bias           | UNEXPECTED |
predictions.decoder.bias         | UNEXPECTED |
predictions.dense.weight         | UNEXPECTED |
sop_classifier.classifier.bias   | UNEXPECTED |
sop_classifier.classifier.weight | UNEXPECTED |
predictions.decoder.weight       | UNEXPECTED |
predictions.bias                 | UNEXPECTED |
classifier.weight                | MISSING    |
classifier.bias                  | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 99,842 || all params: 33,544,964 || trainable%: 0.2976
   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(5.003508771929824)]
🚀 Training...

⏸️  Recall hasn't improved for 2 evals. Best: 0.9016

⏸️  Recall hasn't improved for 2 evals. Best: 0.9016
   ✅ Training done — loss: 0.1525

📊 Test Set Results:
   Accuracy   : 0.8965
   F1 Macro   : 0.8416
   Class 0 — Prec: 0.9838  Rec: 0.8905  F1: 0.9348
   Class 1 — Prec: 0.6278  Rec: 0.9262  F1: 0.7483
   ⚠️  Class 1 recall 0.9262 below 95% target

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9838    0.8905    0.9348       612
           1     0.6278    0.9262    0.7483       122

    accuracy                         0.8965       734
   macro avg     0.8058    0.9084    0.8416       734
weighted avg     0.9246    0.8965    0.9038       734


🔧 LR=0.0007  |  batch_size=64

Loading weights:   0%|          | 0/25 [00:00<?, ?it/s]

AlbertForSequenceClassification LOAD REPORT from: ai4bharat/indic-bert
Key                              | Status     |
---------------------------------+------------+-
predictions.LayerNorm.weight     | UNEXPECTED |
predictions.LayerNorm.bias       | UNEXPECTED |
predictions.dense.bias           | UNEXPECTED |
predictions.decoder.bias         | UNEXPECTED |
predictions.dense.weight         | UNEXPECTED |
sop_classifier.classifier.bias   | UNEXPECTED |
sop_classifier.classifier.weight | UNEXPECTED |
predictions.decoder.weight       | UNEXPECTED |
predictions.bias                 | UNEXPECTED |
classifier.weight                | MISSING    |
classifier.bias                  | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 99,842 || all params: 33,544,964 || trainable%: 0.2976
   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(5.003508771929824)]
🚀 Training...

⏸️  Recall hasn't improved for 2 evals. Best: 0.9016
   ✅ Training done — loss: 0.1880

📊 Test Set Results:
   Accuracy   : 0.9537
   F1 Macro   : 0.9210
   Class 0 — Prec: 0.9865  Rec: 0.9575  F1: 0.9718
   Class 1 — Prec: 0.8143  Rec: 0.9344  F1: 0.8702
   ⚠️  Class 1 recall 0.9344 below 95% target

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9865    0.9575    0.9718       612
           1     0.8143    0.9344    0.8702       122

    accuracy                         0.9537       734
   macro avg     0.9004    0.9460    0.9210       734
weighted avg     0.9579    0.9537    0.9549       734


🔧 Attempting threshold adjustment to reach 95% recall...

============================================================
🎯 THRESHOLD OPTIMIZATION FOR 95% RECALL
============================================================

📊 Optimal threshold : 0.2724
   Accuracy          : 0.8243
   Class 0 — Prec: 0.9899  Rec: 0.7974  F1: 0.8833
   Class 1 — Prec: 0.4855  Rec: 0.9590  F1: 0.6446  ✅ MEETS TARGET!

   Confusion Matrix:
[[488 124]
 [  5 117]]
   TN:488  FP:124  FN:5  TP:117

              precision    recall  f1-score   support

           0     0.9899    0.7974    0.8833       612
           1     0.4855    0.9590    0.6446       122

    accuracy                         0.8243       734
   macro avg     0.7377    0.8782    0.7639       734
weighted avg     0.9060    0.8243    0.8436       734


============================================================
📊 GRID SEARCH SUMMARY — TAMIL / INDICBERT
============================================================
    LR  Batch Size Accuracy F1 Macro Recall (C1) F1 (C1) Precision (C1)
0.0003          32   0.6035   0.5624      0.8934  0.4283         0.2817
0.0003          64   0.6104   0.5654      0.8689  0.4257         0.2819
0.0005          32   0.8692   0.8073      0.9098  0.6981         0.5663
0.0005          64   0.5681   0.5368      0.9262  0.4162         0.2684
0.0007          32   0.8965   0.8416      0.9262  0.7483         0.6278
0.0007          64   0.9537   0.9210      0.9590  0.6446         0.4855

💾 Results saved to lora_results_Tamil_indicbert.csv

============================================================
🏅 BEST RUN — LR=0.0007, batch_size=64
============================================================
   Accuracy  : 0.9537
   F1 Macro  : 0.9210
   Class 0 — Prec:0.9865  Rec:0.9575  F1:0.9718
   Class 1 — Prec:0.4855  Rec:0.9590  F1:0.6446
   Applied threshold : 0.2724
✅ Best model saved to: /content/drive/MyDrive/Models/Tamil_indicbert_lora/Tamil_indicbert_best

🔄 Tokenizing datasets...

Map:   0%|          | 0/3422 [00:00<?, ? examples/s]

Map:   0%|          | 0/734 [00:00<?, ? examples/s]

Map:   0%|          | 0/734 [00:00<?, ? examples/s]

   ✅ Train : 3,422   Val : 734   Test : 734

############################################################
# LANGUAGE : Tamil  |  MODEL : xlm-roberta
# xlm-roberta-base
# Batch sizes    : [32, 64]
# Learning rates : [0.0003, 0.0005, 0.0007]
# Focal gamma    : 2.5  |  Minority boost: 1.0×
# Early stop on Class-1 recall >= 95%
############################################################

🔧 LR=0.0003  |  batch_size=32

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForSequenceClassification LOAD REPORT from: xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
classifier.out_proj.bias    | MISSING    |
classifier.dense.weight     | MISSING    |
classifier.dense.bias       | MISSING    |
classifier.out_proj.weight  | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 1,181,954 || all params: 279,227,140 || trainable%: 0.4233
   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(5.003508771929824)]
🚀 Training...

🎯 Target recall 95.00% achieved! Current: 0.9508
   Stopping training early...
   ✅ Training done — loss: 0.1659

📊 Test Set Results:
   Accuracy   : 0.9659
   F1 Macro   : 0.9418
   Class 0 — Prec: 0.9933  Rec: 0.9657  F1: 0.9793
   Class 1 — Prec: 0.8489  Rec: 0.9672  F1: 0.9042
   ✅ Class 1 recall 0.9672 meets target!

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9933    0.9657    0.9793       612
           1     0.8489    0.9672    0.9042       122

    accuracy                         0.9659       734
   macro avg     0.9211    0.9664    0.9418       734
weighted avg     0.9693    0.9659    0.9668       734


🔧 LR=0.0003  |  batch_size=64

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForSequenceClassification LOAD REPORT from: xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
classifier.out_proj.bias    | MISSING    |
classifier.dense.weight     | MISSING    |
classifier.dense.bias       | MISSING    |
classifier.out_proj.weight  | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 1,181,954 || all params: 279,227,140 || trainable%: 0.4233
   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(5.003508771929824)]
🚀 Training...

🎯 Target recall 95.00% achieved! Current: 0.9508
   Stopping training early...
   ✅ Training done — loss: 0.2055

📊 Test Set Results:
   Accuracy   : 0.9319
   F1 Macro   : 0.8914
   Class 0 — Prec: 0.9930  Rec: 0.9248  F1: 0.9577
   Class 1 — Prec: 0.7195  Rec: 0.9672  F1: 0.8252
   ✅ Class 1 recall 0.9672 meets target!

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9930    0.9248    0.9577       612
           1     0.7195    0.9672    0.8252       122

    accuracy                         0.9319       734
   macro avg     0.8562    0.9460    0.8914       734
weighted avg     0.9475    0.9319    0.9357       734


🔧 LR=0.0005  |  batch_size=32

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForSequenceClassification LOAD REPORT from: xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
classifier.out_proj.bias    | MISSING    |
classifier.dense.weight     | MISSING    |
classifier.dense.bias       | MISSING    |
classifier.out_proj.weight  | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 1,181,954 || all params: 279,227,140 || trainable%: 0.4233
   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(5.003508771929824)]
🚀 Training...

🎯 Target recall 95.00% achieved! Current: 0.9590
   Stopping training early...
   ✅ Training done — loss: 0.3284

📊 Test Set Results:
   Accuracy   : 0.8924
   F1 Macro   : 0.8403
   Class 0 — Prec: 0.9926  Rec: 0.8775  F1: 0.9315
   Class 1 — Prec: 0.6114  Rec: 0.9672  F1: 0.7492
   ✅ Class 1 recall 0.9672 meets target!

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9926    0.8775    0.9315       612
           1     0.6114    0.9672    0.7492       122

    accuracy                         0.8924       734
   macro avg     0.8020    0.9223    0.8403       734
weighted avg     0.9292    0.8924    0.9012       734


🔧 LR=0.0005  |  batch_size=64

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForSequenceClassification LOAD REPORT from: xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
classifier.out_proj.bias    | MISSING    |
classifier.dense.weight     | MISSING    |
classifier.dense.bias       | MISSING    |
classifier.out_proj.weight  | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 1,181,954 || all params: 279,227,140 || trainable%: 0.4233
   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(5.003508771929824)]
🚀 Training...

🎯 Target recall 95.00% achieved! Current: 0.9508
   Stopping training early...
   ✅ Training done — loss: 0.1425

📊 Test Set Results:
   Accuracy   : 0.9687
   F1 Macro   : 0.9458
   Class 0 — Prec: 0.9917  Rec: 0.9706  F1: 0.9810
   Class 1 — Prec: 0.8667  Rec: 0.9590  F1: 0.9105
   ✅ Class 1 recall 0.9590 meets target!

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9917    0.9706    0.9810       612
           1     0.8667    0.9590    0.9105       122

    accuracy                         0.9687       734
   macro avg     0.9292    0.9648    0.9458       734
weighted avg     0.9709    0.9687    0.9693       734


🔧 LR=0.0007  |  batch_size=32

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForSequenceClassification LOAD REPORT from: xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
classifier.out_proj.bias    | MISSING    |
classifier.dense.weight     | MISSING    |
classifier.dense.bias       | MISSING    |
classifier.out_proj.weight  | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 1,181,954 || all params: 279,227,140 || trainable%: 0.4233
   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(5.003508771929824)]
🚀 Training...

🎯 Target recall 95.00% achieved! Current: 0.9672
   Stopping training early...
   ✅ Training done — loss: 0.2104

📊 Test Set Results:
   Accuracy   : 0.9251
   F1 Macro   : 0.8821
   Class 0 — Prec: 0.9929  Rec: 0.9167  F1: 0.9533
   Class 1 — Prec: 0.6982  Rec: 0.9672  F1: 0.8110
   ✅ Class 1 recall 0.9672 meets target!

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9929    0.9167    0.9533       612
           1     0.6982    0.9672    0.8110       122

    accuracy                         0.9251       734
   macro avg     0.8456    0.9419    0.8821       734
weighted avg     0.9439    0.9251    0.9296       734


🔧 LR=0.0007  |  batch_size=64

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForSequenceClassification LOAD REPORT from: xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
classifier.out_proj.bias    | MISSING    |
classifier.dense.weight     | MISSING    |
classifier.dense.bias       | MISSING    |
classifier.out_proj.weight  | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 1,181,954 || all params: 279,227,140 || trainable%: 0.4233
   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(5.003508771929824)]
🚀 Training...

🎯 Target recall 95.00% achieved! Current: 0.9754
   Stopping training early...
   ✅ Training done — loss: 0.3528

📊 Test Set Results:
   Accuracy   : 0.9087
   F1 Macro   : 0.8600
   Class 0 — Prec: 0.9910  Rec: 0.8987  F1: 0.9426
   Class 1 — Prec: 0.6536  Rec: 0.9590  F1: 0.7774
   ✅ Class 1 recall 0.9590 meets target!

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9910    0.8987    0.9426       612
           1     0.6536    0.9590    0.7774       122

    accuracy                         0.9087       734
   macro avg     0.8223    0.9289    0.8600       734
weighted avg     0.9349    0.9087    0.9151       734


============================================================
📊 GRID SEARCH SUMMARY — TAMIL / XLM-ROBERTA
============================================================
    LR  Batch Size Accuracy F1 Macro Recall (C1) F1 (C1) Precision (C1)
0.0003          32   0.9659   0.9418      0.9672  0.9042         0.8489
0.0003          64   0.9319   0.8914      0.9672  0.8252         0.7195
0.0005          32   0.8924   0.8403      0.9672  0.7492         0.6114
0.0005          64   0.9687   0.9458      0.9590  0.9105         0.8667
0.0007          32   0.9251   0.8821      0.9672  0.8110         0.6982
0.0007          64   0.9087   0.8600      0.9590  0.7774         0.6536

💾 Results saved to lora_results_Tamil_xlm-roberta.csv

============================================================
🏅 BEST RUN — LR=0.0003, batch_size=32
============================================================
   Accuracy  : 0.9659
   F1 Macro  : 0.9418
   Class 0 — Prec:0.9933  Rec:0.9657  F1:0.9793
   Class 1 — Prec:0.8489  Rec:0.9672  F1:0.9042
✅ Best model saved to: /content/drive/MyDrive/Models/Tamil_xlm-roberta_lora/Tamil_xlm-roberta_best

============================================================
  LOADING DATASET FOR LANGUAGE: Telugu
============================================================

============================================================
📂 DATASET LOADING WITH STRATIFICATION
============================================================

📊 Original dataset : 4,966 rows
   Class 0: 4,173  (84.0%)
   Class 1: 793  (16.0%)

   ⚠️  Imbalance ratio: 5.26:1  → Focal Loss will help

   TRAIN (3,476):
      Class 0: 2,921  (84.0%)
      Class 1: 555  (16.0%)

   VAL (745):
      Class 0: 626  (84.0%)
      Class 1: 119  (16.0%)

   TEST (745):
      Class 0: 626  (84.0%)
      Class 1: 119  (16.0%)

📊 Class weights (minority boost=1.0×): [np.float64(1.0), np.float64(5.263063063063063)]
💾 Splits saved to /content/drive/MyDrive/Models/splits_telugu/

🔄 Tokenizing datasets...

Map:   0%|          | 0/3476 [00:00<?, ? examples/s]

Map:   0%|          | 0/745 [00:00<?, ? examples/s]

Map:   0%|          | 0/745 [00:00<?, ? examples/s]

   ✅ Train : 3,476   Val : 745   Test : 745

############################################################
# LANGUAGE : Telugu  |  MODEL : mdeberta
# microsoft/mdeberta-v3-base
# Batch sizes    : [32, 64]
# Learning rates : [0.0003, 0.0005, 0.0007]
# Focal gamma    : 2.5  |  Minority boost: 1.0×
# Early stop on Class-1 recall >= 95%
############################################################

🔧 LR=0.0003  |  batch_size=32

Loading weights:   0%|          | 0/198 [00:00<?, ?it/s]

DebertaV2ForSequenceClassification LOAD REPORT from: microsoft/mdeberta-v3-base
Key                                        | Status     |
-------------------------------------------+------------+-
mask_predictions.dense.weight              | UNEXPECTED |
mask_predictions.LayerNorm.weight          | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.bias      | UNEXPECTED |
mask_predictions.dense.bias                | UNEXPECTED |
mask_predictions.classifier.bias           | UNEXPECTED |
lm_predictions.lm_head.bias                | UNEXPECTED |
mask_predictions.classifier.weight         | UNEXPECTED |
lm_predictions.lm_head.dense.weight        | UNEXPECTED |
lm_predictions.lm_head.dense.bias          | UNEXPECTED |
mask_predictions.LayerNorm.bias            | UNEXPECTED |
deberta.embeddings.word_embeddings._weight | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.weight    | UNEXPECTED |
pooler.dense.weight                        | MISSING    |
pooler.dense.bias                          | MISSING    |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 591,362 || all params: 279,402,244 || trainable%: 0.2117

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 2, 'bos_token_id': 1}.

   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(5.263063063063063)]
🚀 Training...

🎯 Target recall 95.00% achieved! Current: 0.9580
   Stopping training early...
   ✅ Training done — loss: 0.1840

📊 Test Set Results:
   Accuracy   : 0.9651
   F1 Macro   : 0.9371
   Class 0 — Prec: 0.9870  Rec: 0.9712  F1: 0.9791
   Class 1 — Prec: 0.8605  Rec: 0.9328  F1: 0.8952
   ⚠️  Class 1 recall 0.9328 below 95% target

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9870    0.9712    0.9791       626
           1     0.8605    0.9328    0.8952       119

    accuracy                         0.9651       745
   macro avg     0.9237    0.9520    0.9371       745
weighted avg     0.9668    0.9651    0.9657       745


🔧 LR=0.0003  |  batch_size=64

Loading weights:   0%|          | 0/198 [00:00<?, ?it/s]

DebertaV2ForSequenceClassification LOAD REPORT from: microsoft/mdeberta-v3-base
Key                                        | Status     |
-------------------------------------------+------------+-
mask_predictions.dense.weight              | UNEXPECTED |
mask_predictions.LayerNorm.weight          | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.bias      | UNEXPECTED |
mask_predictions.dense.bias                | UNEXPECTED |
mask_predictions.classifier.bias           | UNEXPECTED |
lm_predictions.lm_head.bias                | UNEXPECTED |
mask_predictions.classifier.weight         | UNEXPECTED |
lm_predictions.lm_head.dense.weight        | UNEXPECTED |
lm_predictions.lm_head.dense.bias          | UNEXPECTED |
mask_predictions.LayerNorm.bias            | UNEXPECTED |
deberta.embeddings.word_embeddings._weight | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.weight    | UNEXPECTED |
pooler.dense.weight                        | MISSING    |
pooler.dense.bias                          | MISSING    |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 591,362 || all params: 279,402,244 || trainable%: 0.2117

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 2, 'bos_token_id': 1}.

   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(5.263063063063063)]
🚀 Training...

⏸️  Recall hasn't improved for 2 evals. Best: 0.9412

⏸️  Recall hasn't improved for 2 evals. Best: 0.9412

⏸️  Recall hasn't improved for 2 evals. Best: 0.9412
   ✅ Training done — loss: 0.2256

📊 Test Set Results:
   Accuracy   : 0.8483
   F1 Macro   : 0.7786
   Class 0 — Prec: 0.9777  Rec: 0.8387  F1: 0.9028
   Class 1 — Prec: 0.5144  Rec: 0.8992  F1: 0.6544
   ⚠️  Class 1 recall 0.8992 below 95% target

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9777    0.8387    0.9028       626
           1     0.5144    0.8992    0.6544       119

    accuracy                         0.8483       745
   macro avg     0.7460    0.8689    0.7786       745
weighted avg     0.9037    0.8483    0.8632       745


🔧 LR=0.0005  |  batch_size=32

Loading weights:   0%|          | 0/198 [00:00<?, ?it/s]

DebertaV2ForSequenceClassification LOAD REPORT from: microsoft/mdeberta-v3-base
Key                                        | Status     |
-------------------------------------------+------------+-
mask_predictions.dense.weight              | UNEXPECTED |
mask_predictions.LayerNorm.weight          | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.bias      | UNEXPECTED |
mask_predictions.dense.bias                | UNEXPECTED |
mask_predictions.classifier.bias           | UNEXPECTED |
lm_predictions.lm_head.bias                | UNEXPECTED |
mask_predictions.classifier.weight         | UNEXPECTED |
lm_predictions.lm_head.dense.weight        | UNEXPECTED |
lm_predictions.lm_head.dense.bias          | UNEXPECTED |
mask_predictions.LayerNorm.bias            | UNEXPECTED |
deberta.embeddings.word_embeddings._weight | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.weight    | UNEXPECTED |
pooler.dense.weight                        | MISSING    |
pooler.dense.bias                          | MISSING    |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 591,362 || all params: 279,402,244 || trainable%: 0.2117

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 2, 'bos_token_id': 1}.

   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(5.263063063063063)]
🚀 Training...

⏸️  Recall hasn't improved for 2 evals. Best: 0.9496
   ✅ Training done — loss: 0.1600

📊 Test Set Results:
   Accuracy   : 0.9597
   F1 Macro   : 0.9293
   Class 0 — Prec: 0.9901  Rec: 0.9617  F1: 0.9757
   Class 1 — Prec: 0.8248  Rec: 0.9496  F1: 0.8828
   ⚠️  Class 1 recall 0.9496 below 95% target

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9901    0.9617    0.9757       626
           1     0.8248    0.9496    0.8828       119

    accuracy                         0.9597       745
   macro avg     0.9075    0.9556    0.9293       745
weighted avg     0.9637    0.9597    0.9609       745


🔧 LR=0.0005  |  batch_size=64

Loading weights:   0%|          | 0/198 [00:00<?, ?it/s]

DebertaV2ForSequenceClassification LOAD REPORT from: microsoft/mdeberta-v3-base
Key                                        | Status     |
-------------------------------------------+------------+-
mask_predictions.dense.weight              | UNEXPECTED |
mask_predictions.LayerNorm.weight          | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.bias      | UNEXPECTED |
mask_predictions.dense.bias                | UNEXPECTED |
mask_predictions.classifier.bias           | UNEXPECTED |
lm_predictions.lm_head.bias                | UNEXPECTED |
mask_predictions.classifier.weight         | UNEXPECTED |
lm_predictions.lm_head.dense.weight        | UNEXPECTED |
lm_predictions.lm_head.dense.bias          | UNEXPECTED |
mask_predictions.LayerNorm.bias            | UNEXPECTED |
deberta.embeddings.word_embeddings._weight | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.weight    | UNEXPECTED |
pooler.dense.weight                        | MISSING    |
pooler.dense.bias                          | MISSING    |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 591,362 || all params: 279,402,244 || trainable%: 0.2117

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 2, 'bos_token_id': 1}.

   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(5.263063063063063)]
🚀 Training...

🎯 Target recall 95.00% achieved! Current: 0.9832
   Stopping training early...
   ✅ Training done — loss: 0.2451

📊 Test Set Results:
   Accuracy   : 0.9235
   F1 Macro   : 0.8750
   Class 0 — Prec: 0.9880  Rec: 0.9201  F1: 0.9529
   Class 1 — Prec: 0.6914  Rec: 0.9412  F1: 0.7972
   ⚠️  Class 1 recall 0.9412 below 95% target

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9880    0.9201    0.9529       626
           1     0.6914    0.9412    0.7972       119

    accuracy                         0.9235       745
   macro avg     0.8397    0.9307    0.8750       745
weighted avg     0.9406    0.9235    0.9280       745


🔧 LR=0.0007  |  batch_size=32

Loading weights:   0%|          | 0/198 [00:00<?, ?it/s]

DebertaV2ForSequenceClassification LOAD REPORT from: microsoft/mdeberta-v3-base
Key                                        | Status     |
-------------------------------------------+------------+-
mask_predictions.dense.weight              | UNEXPECTED |
mask_predictions.LayerNorm.weight          | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.bias      | UNEXPECTED |
mask_predictions.dense.bias                | UNEXPECTED |
mask_predictions.classifier.bias           | UNEXPECTED |
lm_predictions.lm_head.bias                | UNEXPECTED |
mask_predictions.classifier.weight         | UNEXPECTED |
lm_predictions.lm_head.dense.weight        | UNEXPECTED |
lm_predictions.lm_head.dense.bias          | UNEXPECTED |
mask_predictions.LayerNorm.bias            | UNEXPECTED |
deberta.embeddings.word_embeddings._weight | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.weight    | UNEXPECTED |
pooler.dense.weight                        | MISSING    |
pooler.dense.bias                          | MISSING    |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 591,362 || all params: 279,402,244 || trainable%: 0.2117

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 2, 'bos_token_id': 1}.

   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(5.263063063063063)]
🚀 Training...

🎯 Target recall 95.00% achieved! Current: 0.9748
   Stopping training early...
   ✅ Training done — loss: 0.2331

📊 Test Set Results:
   Accuracy   : 0.9477
   F1 Macro   : 0.9115
   Class 0 — Prec: 0.9933  Rec: 0.9441  F1: 0.9681
   Class 1 — Prec: 0.7667  Rec: 0.9664  F1: 0.8550
   ✅ Class 1 recall 0.9664 meets target!

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9933    0.9441    0.9681       626
           1     0.7667    0.9664    0.8550       119

    accuracy                         0.9477       745
   macro avg     0.8800    0.9552    0.9115       745
weighted avg     0.9571    0.9477    0.9500       745


🔧 LR=0.0007  |  batch_size=64

Loading weights:   0%|          | 0/198 [00:00<?, ?it/s]

DebertaV2ForSequenceClassification LOAD REPORT from: microsoft/mdeberta-v3-base
Key                                        | Status     |
-------------------------------------------+------------+-
mask_predictions.dense.weight              | UNEXPECTED |
mask_predictions.LayerNorm.weight          | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.bias      | UNEXPECTED |
mask_predictions.dense.bias                | UNEXPECTED |
mask_predictions.classifier.bias           | UNEXPECTED |
lm_predictions.lm_head.bias                | UNEXPECTED |
mask_predictions.classifier.weight         | UNEXPECTED |
lm_predictions.lm_head.dense.weight        | UNEXPECTED |
lm_predictions.lm_head.dense.bias          | UNEXPECTED |
mask_predictions.LayerNorm.bias            | UNEXPECTED |
deberta.embeddings.word_embeddings._weight | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.weight    | UNEXPECTED |
pooler.dense.weight                        | MISSING    |
pooler.dense.bias                          | MISSING    |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 591,362 || all params: 279,402,244 || trainable%: 0.2117

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 2, 'bos_token_id': 1}.

   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(5.263063063063063)]
🚀 Training...

🎯 Target recall 95.00% achieved! Current: 0.9748
   Stopping training early...
   ✅ Training done — loss: 0.3232

📊 Test Set Results:
   Accuracy   : 0.8456
   F1 Macro   : 0.7831
   Class 0 — Prec: 0.9923  Rec: 0.8227  F1: 0.8996
   Class 1 — Prec: 0.5088  Rec: 0.9664  F1: 0.6667
   ✅ Class 1 recall 0.9664 meets target!

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9923    0.8227    0.8996       626
           1     0.5088    0.9664    0.6667       119

    accuracy                         0.8456       745
   macro avg     0.7506    0.8945    0.7831       745
weighted avg     0.9151    0.8456    0.8624       745


============================================================
📊 GRID SEARCH SUMMARY — TELUGU / MDEBERTA
============================================================
    LR  Batch Size Accuracy F1 Macro Recall (C1) F1 (C1) Precision (C1)
0.0003          32   0.9651   0.9371      0.9328  0.8952         0.8605
0.0003          64   0.8483   0.7786      0.8992  0.6544         0.5144
0.0005          32   0.9597   0.9293      0.9496  0.8828         0.8248
0.0005          64   0.9235   0.8750      0.9412  0.7972         0.6914
0.0007          32   0.9477   0.9115      0.9664  0.8550         0.7667
0.0007          64   0.8456   0.7831      0.9664  0.6667         0.5088

💾 Results saved to lora_results_Telugu_mdeberta.csv

============================================================
🏅 BEST RUN — LR=0.0007, batch_size=32
============================================================
   Accuracy  : 0.9477
   F1 Macro  : 0.9115
   Class 0 — Prec:0.9933  Rec:0.9441  F1:0.9681
   Class 1 — Prec:0.7667  Rec:0.9664  F1:0.8550
✅ Best model saved to: /content/drive/MyDrive/Models/Telugu_mdeberta_lora/Telugu_mdeberta_best

🔄 Tokenizing datasets...

Map:   0%|          | 0/3476 [00:00<?, ? examples/s]

Map:   0%|          | 0/745 [00:00<?, ? examples/s]

Map:   0%|          | 0/745 [00:00<?, ? examples/s]

   ✅ Train : 3,476   Val : 745   Test : 745

############################################################
# LANGUAGE : Telugu  |  MODEL : indicbert
# ai4bharat/indic-bert
# Batch sizes    : [32, 64]
# Learning rates : [0.0003, 0.0005, 0.0007]
# Focal gamma    : 2.5  |  Minority boost: 1.0×
# Early stop on Class-1 recall >= 95%
############################################################

🔧 LR=0.0003  |  batch_size=32

Loading weights:   0%|          | 0/25 [00:00<?, ?it/s]

AlbertForSequenceClassification LOAD REPORT from: ai4bharat/indic-bert
Key                              | Status     |
---------------------------------+------------+-
predictions.LayerNorm.weight     | UNEXPECTED |
predictions.LayerNorm.bias       | UNEXPECTED |
predictions.dense.bias           | UNEXPECTED |
predictions.decoder.bias         | UNEXPECTED |
predictions.dense.weight         | UNEXPECTED |
sop_classifier.classifier.bias   | UNEXPECTED |
sop_classifier.classifier.weight | UNEXPECTED |
predictions.decoder.weight       | UNEXPECTED |
predictions.bias                 | UNEXPECTED |
classifier.weight                | MISSING    |
classifier.bias                  | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 99,842 || all params: 33,544,964 || trainable%: 0.2976
   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(5.263063063063063)]
🚀 Training...

⏸️  Recall hasn't improved for 2 evals. Best: 0.8739
   ✅ Training done — loss: 0.2245

📊 Test Set Results:
   Accuracy   : 0.9436
   F1 Macro   : 0.9022
   Class 0 — Prec: 0.9834  Rec: 0.9489  F1: 0.9659
   Class 1 — Prec: 0.7730  Rec: 0.9160  F1: 0.8385
   ⚠️  Class 1 recall 0.9160 below 95% target

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9834    0.9489    0.9659       626
           1     0.7730    0.9160    0.8385       119

    accuracy                         0.9436       745
   macro avg     0.8782    0.9324    0.9022       745
weighted avg     0.9498    0.9436    0.9455       745


🔧 LR=0.0003  |  batch_size=64

Loading weights:   0%|          | 0/25 [00:00<?, ?it/s]

AlbertForSequenceClassification LOAD REPORT from: ai4bharat/indic-bert
Key                              | Status     |
---------------------------------+------------+-
predictions.LayerNorm.weight     | UNEXPECTED |
predictions.LayerNorm.bias       | UNEXPECTED |
predictions.dense.bias           | UNEXPECTED |
predictions.decoder.bias         | UNEXPECTED |
predictions.dense.weight         | UNEXPECTED |
sop_classifier.classifier.bias   | UNEXPECTED |
sop_classifier.classifier.weight | UNEXPECTED |
predictions.decoder.weight       | UNEXPECTED |
predictions.bias                 | UNEXPECTED |
classifier.weight                | MISSING    |
classifier.bias                  | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 99,842 || all params: 33,544,964 || trainable%: 0.2976
   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(5.263063063063063)]
🚀 Training...

🎯 Target recall 95.00% achieved! Current: 1.0000
   Stopping training early...
   ✅ Training done — loss: 0.5556

📊 Test Set Results:
   Accuracy   : 0.1597
   F1 Macro   : 0.1377
   Class 0 — Prec: 0.0000  Rec: 0.0000  F1: 0.0000
   Class 1 — Prec: 0.1597  Rec: 1.0000  F1: 0.2755
   ✅ Class 1 recall 1.0000 meets target!

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.0000    0.0000    0.0000       626
           1     0.1597    1.0000    0.2755       119

    accuracy                         0.1597       745
   macro avg     0.0799    0.5000    0.1377       745
weighted avg     0.0255    0.1597    0.0440       745


🔧 LR=0.0005  |  batch_size=32

Loading weights:   0%|          | 0/25 [00:00<?, ?it/s]

AlbertForSequenceClassification LOAD REPORT from: ai4bharat/indic-bert
Key                              | Status     |
---------------------------------+------------+-
predictions.LayerNorm.weight     | UNEXPECTED |
predictions.LayerNorm.bias       | UNEXPECTED |
predictions.dense.bias           | UNEXPECTED |
predictions.decoder.bias         | UNEXPECTED |
predictions.dense.weight         | UNEXPECTED |
sop_classifier.classifier.bias   | UNEXPECTED |
sop_classifier.classifier.weight | UNEXPECTED |
predictions.decoder.weight       | UNEXPECTED |
predictions.bias                 | UNEXPECTED |
classifier.weight                | MISSING    |
classifier.bias                  | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 99,842 || all params: 33,544,964 || trainable%: 0.2976
   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(5.263063063063063)]
🚀 Training...

⏸️  Recall hasn't improved for 2 evals. Best: 0.9496
   ✅ Training done — loss: 0.1805

📊 Test Set Results:
   Accuracy   : 0.9423
   F1 Macro   : 0.9030
   Class 0 — Prec: 0.9916  Rec: 0.9393  F1: 0.9647
   Class 1 — Prec: 0.7500  Rec: 0.9580  F1: 0.8413
   ✅ Class 1 recall 0.9580 meets target!

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9916    0.9393    0.9647       626
           1     0.7500    0.9580    0.8413       119

    accuracy                         0.9423       745
   macro avg     0.8708    0.9486    0.9030       745
weighted avg     0.9530    0.9423    0.9450       745


🔧 LR=0.0005  |  batch_size=64

Loading weights:   0%|          | 0/25 [00:00<?, ?it/s]

AlbertForSequenceClassification LOAD REPORT from: ai4bharat/indic-bert
Key                              | Status     |
---------------------------------+------------+-
predictions.LayerNorm.weight     | UNEXPECTED |
predictions.LayerNorm.bias       | UNEXPECTED |
predictions.dense.bias           | UNEXPECTED |
predictions.decoder.bias         | UNEXPECTED |
predictions.dense.weight         | UNEXPECTED |
sop_classifier.classifier.bias   | UNEXPECTED |
sop_classifier.classifier.weight | UNEXPECTED |
predictions.decoder.weight       | UNEXPECTED |
predictions.bias                 | UNEXPECTED |
classifier.weight                | MISSING    |
classifier.bias                  | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 99,842 || all params: 33,544,964 || trainable%: 0.2976
   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(5.263063063063063)]
🚀 Training...

🎯 Target recall 95.00% achieved! Current: 0.9580
   Stopping training early...
   ✅ Training done — loss: 0.3572

📊 Test Set Results:
   Accuracy   : 0.7785
   F1 Macro   : 0.7176
   Class 0 — Prec: 0.9957  Rec: 0.7396  F1: 0.8488
   Class 1 — Prec: 0.4179  Rec: 0.9832  F1: 0.5865
   ✅ Class 1 recall 0.9832 meets target!

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9957    0.7396    0.8488       626
           1     0.4179    0.9832    0.5865       119

    accuracy                         0.7785       745
   macro avg     0.7068    0.8614    0.7176       745
weighted avg     0.9034    0.7785    0.8069       745


🔧 LR=0.0007  |  batch_size=32

Loading weights:   0%|          | 0/25 [00:00<?, ?it/s]

AlbertForSequenceClassification LOAD REPORT from: ai4bharat/indic-bert
Key                              | Status     |
---------------------------------+------------+-
predictions.LayerNorm.weight     | UNEXPECTED |
predictions.LayerNorm.bias       | UNEXPECTED |
predictions.dense.bias           | UNEXPECTED |
predictions.decoder.bias         | UNEXPECTED |
predictions.dense.weight         | UNEXPECTED |
sop_classifier.classifier.bias   | UNEXPECTED |
sop_classifier.classifier.weight | UNEXPECTED |
predictions.decoder.weight       | UNEXPECTED |
predictions.bias                 | UNEXPECTED |
classifier.weight                | MISSING    |
classifier.bias                  | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 99,842 || all params: 33,544,964 || trainable%: 0.2976
   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(5.263063063063063)]
🚀 Training...

🎯 Target recall 95.00% achieved! Current: 0.9664
   Stopping training early...
   ✅ Training done — loss: 0.2577

📊 Test Set Results:
   Accuracy   : 0.8174
   F1 Macro   : 0.7546
   Class 0 — Prec: 0.9940  Rec: 0.7875  F1: 0.8788
   Class 1 — Prec: 0.4659  Rec: 0.9748  F1: 0.6304
   ✅ Class 1 recall 0.9748 meets target!

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9940    0.7875    0.8788       626
           1     0.4659    0.9748    0.6304       119

    accuracy                         0.8174       745
   macro avg     0.7299    0.8812    0.7546       745
weighted avg     0.9096    0.8174    0.8391       745


🔧 LR=0.0007  |  batch_size=64

Loading weights:   0%|          | 0/25 [00:00<?, ?it/s]

AlbertForSequenceClassification LOAD REPORT from: ai4bharat/indic-bert
Key                              | Status     |
---------------------------------+------------+-
predictions.LayerNorm.weight     | UNEXPECTED |
predictions.LayerNorm.bias       | UNEXPECTED |
predictions.dense.bias           | UNEXPECTED |
predictions.decoder.bias         | UNEXPECTED |
predictions.dense.weight         | UNEXPECTED |
sop_classifier.classifier.bias   | UNEXPECTED |
sop_classifier.classifier.weight | UNEXPECTED |
predictions.decoder.weight       | UNEXPECTED |
predictions.bias                 | UNEXPECTED |
classifier.weight                | MISSING    |
classifier.bias                  | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 99,842 || all params: 33,544,964 || trainable%: 0.2976
   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(5.263063063063063)]
🚀 Training...

⏸️  Recall hasn't improved for 2 evals. Best: 0.9496

⏸️  Recall hasn't improved for 2 evals. Best: 0.9496
   ✅ Training done — loss: 0.2181

📊 Test Set Results:
   Accuracy   : 0.8362
   F1 Macro   : 0.7749
   Class 0 — Prec: 0.9961  Rec: 0.8083  F1: 0.8924
   Class 1 — Prec: 0.4937  Rec: 0.9832  F1: 0.6573
   ✅ Class 1 recall 0.9832 meets target!

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9961    0.8083    0.8924       626
           1     0.4937    0.9832    0.6573       119

    accuracy                         0.8362       745
   macro avg     0.7449    0.8957    0.7749       745
weighted avg     0.9158    0.8362    0.8549       745


============================================================
📊 GRID SEARCH SUMMARY — TELUGU / INDICBERT
============================================================
    LR  Batch Size Accuracy F1 Macro Recall (C1) F1 (C1) Precision (C1)
0.0003          32   0.9436   0.9022      0.9160  0.8385         0.7730
0.0003          64   0.1597   0.1377      1.0000  0.2755         0.1597
0.0005          32   0.9423   0.9030      0.9580  0.8413         0.7500
0.0005          64   0.7785   0.7176      0.9832  0.5865         0.4179
0.0007          32   0.8174   0.7546      0.9748  0.6304         0.4659
0.0007          64   0.8362   0.7749      0.9832  0.6573         0.4937

💾 Results saved to lora_results_Telugu_indicbert.csv

============================================================
🏅 BEST RUN — LR=0.0003, batch_size=64
============================================================
   Accuracy  : 0.1597
   F1 Macro  : 0.1377
   Class 0 — Prec:0.0000  Rec:0.0000  F1:0.0000
   Class 1 — Prec:0.1597  Rec:1.0000  F1:0.2755
✅ Best model saved to: /content/drive/MyDrive/Models/Telugu_indicbert_lora/Telugu_indicbert_best

🔄 Tokenizing datasets...

Map:   0%|          | 0/3476 [00:00<?, ? examples/s]

Map:   0%|          | 0/745 [00:00<?, ? examples/s]

Map:   0%|          | 0/745 [00:00<?, ? examples/s]

   ✅ Train : 3,476   Val : 745   Test : 745

############################################################
# LANGUAGE : Telugu  |  MODEL : xlm-roberta
# xlm-roberta-base
# Batch sizes    : [32, 64]
# Learning rates : [0.0003, 0.0005, 0.0007]
# Focal gamma    : 2.5  |  Minority boost: 1.0×
# Early stop on Class-1 recall >= 95%
############################################################

🔧 LR=0.0003  |  batch_size=32

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForSequenceClassification LOAD REPORT from: xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
classifier.out_proj.bias    | MISSING    |
classifier.dense.weight     | MISSING    |
classifier.dense.bias       | MISSING    |
classifier.out_proj.weight  | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 1,181,954 || all params: 279,227,140 || trainable%: 0.4233
   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(5.263063063063063)]
🚀 Training...

🎯 Target recall 95.00% achieved! Current: 0.9664
   Stopping training early...
   ✅ Training done — loss: 0.2474

📊 Test Set Results:
   Accuracy   : 0.8805
   F1 Macro   : 0.8233
   Class 0 — Prec: 0.9945  Rec: 0.8626  F1: 0.9239
   Class 1 — Prec: 0.5743  Rec: 0.9748  F1: 0.7227
   ✅ Class 1 recall 0.9748 meets target!

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9945    0.8626    0.9239       626
           1     0.5743    0.9748    0.7227       119

    accuracy                         0.8805       745
   macro avg     0.7844    0.9187    0.8233       745
weighted avg     0.9274    0.8805    0.8917       745


🔧 LR=0.0003  |  batch_size=64

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForSequenceClassification LOAD REPORT from: xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
classifier.out_proj.bias    | MISSING    |
classifier.dense.weight     | MISSING    |
classifier.dense.bias       | MISSING    |
classifier.out_proj.weight  | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 1,181,954 || all params: 279,227,140 || trainable%: 0.4233
   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(5.263063063063063)]
🚀 Training...

🎯 Target recall 95.00% achieved! Current: 0.9916
   Stopping training early...
   ✅ Training done — loss: 0.2774

📊 Test Set Results:
   Accuracy   : 0.8711
   F1 Macro   : 0.8124
   Class 0 — Prec: 0.9944  Rec: 0.8514  F1: 0.9174
   Class 1 — Prec: 0.5550  Rec: 0.9748  F1: 0.7073
   ✅ Class 1 recall 0.9748 meets target!

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9944    0.8514    0.9174       626
           1     0.5550    0.9748    0.7073       119

    accuracy                         0.8711       745
   macro avg     0.7747    0.9131    0.8124       745
weighted avg     0.9242    0.8711    0.8838       745


🔧 LR=0.0005  |  batch_size=32

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForSequenceClassification LOAD REPORT from: xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
classifier.out_proj.bias    | MISSING    |
classifier.dense.weight     | MISSING    |
classifier.dense.bias       | MISSING    |
classifier.out_proj.weight  | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 1,181,954 || all params: 279,227,140 || trainable%: 0.4233
   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(5.263063063063063)]
🚀 Training...

🎯 Target recall 95.00% achieved! Current: 0.9580
   Stopping training early...
   ✅ Training done — loss: 0.3500

📊 Test Set Results:
   Accuracy   : 0.9181
   F1 Macro   : 0.8691
   Class 0 — Prec: 0.9913  Rec: 0.9105  F1: 0.9492
   Class 1 — Prec: 0.6706  Rec: 0.9580  F1: 0.7889
   ✅ Class 1 recall 0.9580 meets target!

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9913    0.9105    0.9492       626
           1     0.6706    0.9580    0.7889       119

    accuracy                         0.9181       745
   macro avg     0.8309    0.9343    0.8691       745
weighted avg     0.9401    0.9181    0.9236       745


🔧 LR=0.0005  |  batch_size=64

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForSequenceClassification LOAD REPORT from: xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
classifier.out_proj.bias    | MISSING    |
classifier.dense.weight     | MISSING    |
classifier.dense.bias       | MISSING    |
classifier.out_proj.weight  | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 1,181,954 || all params: 279,227,140 || trainable%: 0.4233
   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(5.263063063063063)]
🚀 Training...

🎯 Target recall 95.00% achieved! Current: 0.9832
   Stopping training early...
   ✅ Training done — loss: 0.2553

📊 Test Set Results:
   Accuracy   : 0.9436
   F1 Macro   : 0.9050
   Class 0 — Prec: 0.9916  Rec: 0.9409  F1: 0.9656
   Class 1 — Prec: 0.7550  Rec: 0.9580  F1: 0.8444
   ✅ Class 1 recall 0.9580 meets target!

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9916    0.9409    0.9656       626
           1     0.7550    0.9580    0.8444       119

    accuracy                         0.9436       745
   macro avg     0.8733    0.9494    0.9050       745
weighted avg     0.9538    0.9436    0.9462       745


🔧 LR=0.0007  |  batch_size=32

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForSequenceClassification LOAD REPORT from: xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
classifier.out_proj.bias    | MISSING    |
classifier.dense.weight     | MISSING    |
classifier.dense.bias       | MISSING    |
classifier.out_proj.weight  | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 1,181,954 || all params: 279,227,140 || trainable%: 0.4233
   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(5.263063063063063)]
🚀 Training...

🎯 Target recall 95.00% achieved! Current: 1.0000
   Stopping training early...
   ✅ Training done — loss: 0.3527

📊 Test Set Results:
   Accuracy   : 0.7664
   F1 Macro   : 0.7064
   Class 0 — Prec: 0.9956  Rec: 0.7252  F1: 0.8392
   Class 1 — Prec: 0.4048  Rec: 0.9832  F1: 0.5735
   ✅ Class 1 recall 0.9832 meets target!

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9956    0.7252    0.8392       626
           1     0.4048    0.9832    0.5735       119

    accuracy                         0.7664       745
   macro avg     0.7002    0.8542    0.7064       745
weighted avg     0.9012    0.7664    0.7968       745


🔧 LR=0.0007  |  batch_size=64

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForSequenceClassification LOAD REPORT from: xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
classifier.out_proj.bias    | MISSING    |
classifier.dense.weight     | MISSING    |
classifier.dense.bias       | MISSING    |
classifier.out_proj.weight  | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 1,181,954 || all params: 279,227,140 || trainable%: 0.4233
   📊 FocalLoss — gamma=2.5, class_weights=[np.float64(1.0), np.float64(5.263063063063063)]
🚀 Training...

🎯 Target recall 95.00% achieved! Current: 0.9748
   Stopping training early...
   ✅ Training done — loss: 0.2731

📊 Test Set Results:
   Accuracy   : 0.9302
   F1 Macro   : 0.8857
   Class 0 — Prec: 0.9914  Rec: 0.9249  F1: 0.9570
   Class 1 — Prec: 0.7081  Rec: 0.9580  F1: 0.8143
   ✅ Class 1 recall 0.9580 meets target!

------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9914    0.9249    0.9570       626
           1     0.7081    0.9580    0.8143       119

    accuracy                         0.9302       745
   macro avg     0.8498    0.9415    0.8857       745
weighted avg     0.9462    0.9302    0.9342       745


============================================================
📊 GRID SEARCH SUMMARY — TELUGU / XLM-ROBERTA
============================================================
    LR  Batch Size Accuracy F1 Macro Recall (C1) F1 (C1) Precision (C1)
0.0003          32   0.8805   0.8233      0.9748  0.7227         0.5743
0.0003          64   0.8711   0.8124      0.9748  0.7073         0.5550
0.0005          32   0.9181   0.8691      0.9580  0.7889         0.6706
0.0005          64   0.9436   0.9050      0.9580  0.8444         0.7550
0.0007          32   0.7664   0.7064      0.9832  0.5735         0.4048
0.0007          64   0.9302   0.8857      0.9580  0.8143         0.7081

💾 Results saved to lora_results_Telugu_xlm-roberta.csv

============================================================
🏅 BEST RUN — LR=0.0007, batch_size=32
============================================================
   Accuracy  : 0.7664
   F1 Macro  : 0.7064
   Class 0 — Prec:0.9956  Rec:0.7252  F1:0.8392
   Class 1 — Prec:0.4048  Rec:0.9832  F1:0.5735
✅ Best model saved to: /content/drive/MyDrive/Models/Telugu_xlm-roberta_lora/Telugu_xlm-roberta_best

############################################################
# ALL 9 EXPERIMENTS COMPLETE!
############################################################

📊 MASTER RESULTS TABLE
Language       Model     LR  Batch Size  Accuracy  F1 Macro  Precision C0  Recall C0  F1 C0  Precision C1  Recall C1  F1 C1 Meets Target
   Hindi    mdeberta 0.0003          32    0.9785    0.9485        0.9869     0.9888 0.9878        0.9155     0.9028 0.9091           ⚠️
   Hindi    mdeberta 0.0003          64    0.9571    0.9074        0.9922     0.9588 0.9752        0.5433     0.9583 0.6935            ✅
   Hindi    mdeberta 0.0005          32    0.9835    0.9591        0.9852     0.9963 0.9907        0.9697     0.8889 0.9275           ⚠️
   Hindi    mdeberta 0.0005          64    0.9752    0.9405        0.9850     0.9869 0.9860        0.9014     0.8889 0.8951           ⚠️
   Hindi    mdeberta 0.0007          32    0.9637    0.9182        0.9885     0.9700 0.9792        0.8049     0.9167 0.8571           ⚠️
   Hindi    mdeberta 0.0007          64    0.9752    0.9405        0.9850     0.9869 0.9860        0.9014     0.8889 0.8951           ⚠️
   Hindi   indicbert 0.0003          32    0.9092    0.8291        0.9918     0.9045 0.9461        0.5714     0.9444 0.7120           ⚠️
   Hindi   indicbert 0.0003          64    0.9323    0.8644        0.9920     0.9307 0.9604        0.6476     0.9444 0.7684           ⚠️
   Hindi   indicbert 0.0005          32    0.7871    0.6934        0.9975     0.7603 0.8629        0.3568     0.9861 0.5240            ✅
   Hindi   indicbert 0.0005          64    0.7640    0.6720        0.9975     0.7341 0.8457        0.3333     0.9861 0.4982            ✅
   Hindi   indicbert 0.0007          32    0.1188    0.1062        0.0000     0.0000 0.0000        0.1188     1.0000 0.2124            ✅
   Hindi   indicbert 0.0007          64    0.6848    0.6046        0.9971     0.6442 0.7827        0.2720     0.9861 0.4264            ✅
   Hindi xlm-roberta 0.0003          32    0.9818    0.9569        0.9906     0.9888 0.9897        0.9178     0.9306 0.9241           ⚠️
   Hindi xlm-roberta 0.0003          64    0.8053    0.7111        0.9976     0.7809 0.8761        0.3777     0.9861 0.5462            ✅
   Hindi xlm-roberta 0.0005          32    0.9884    0.9726        0.9944     0.9925 0.9934        0.9452     0.9583 0.9517            ✅
   Hindi xlm-roberta 0.0005          64    0.8762    0.7864        0.9935     0.8652 0.9249        0.4894     0.9583 0.6479            ✅
   Hindi xlm-roberta 0.0007          32    0.9851    0.9652        0.9944     0.9888 0.9915        0.9200     0.9583 0.9388            ✅
   Hindi xlm-roberta 0.0007          64    0.9307    0.8642        0.9960     0.9251 0.9592        0.6364     0.9722 0.7692            ✅
   Tamil    mdeberta 0.0003          32    0.9728    0.9518        0.9884     0.9788 0.9836        0.8984     0.9426 0.9200           ⚠️
   Tamil    mdeberta 0.0003          64    0.9305    0.8853        0.9811     0.9346 0.9573        0.7351     0.9098 0.8132           ⚠️
   Tamil    mdeberta 0.0005          32    0.9646    0.9389        0.9900     0.9673 0.9785        0.8529     0.9508 0.8992            ✅
   Tamil    mdeberta 0.0005          64    0.8025    0.7412        0.9875     0.7729 0.8671        0.4549     0.9508 0.6154            ✅
   Tamil    mdeberta 0.0007          32    0.9673    0.9432        0.9900     0.9706 0.9802        0.8657     0.9508 0.9062            ✅
   Tamil    mdeberta 0.0007          64    0.9632    0.9371        0.9916     0.9641 0.9776        0.8417     0.9590 0.8966            ✅
   Tamil   indicbert 0.0003          32    0.6035    0.5624        0.9625     0.5458 0.6966        0.2817     0.8934 0.4283           ⚠️
   Tamil   indicbert 0.0003          64    0.6104    0.5654        0.9553     0.5588 0.7052        0.2819     0.8689 0.4257           ⚠️
   Tamil   indicbert 0.0005          32    0.8692    0.8073        0.9796     0.8611 0.9165        0.5663     0.9098 0.6981           ⚠️
   Tamil   indicbert 0.0005          64    0.5681    0.5368        0.9712     0.4967 0.6573        0.2684     0.9262 0.4162           ⚠️
   Tamil   indicbert 0.0007          32    0.8965    0.8416        0.9838     0.8905 0.9348        0.6278     0.9262 0.7483           ⚠️
   Tamil   indicbert 0.0007          64    0.9537    0.9210        0.9865     0.9575 0.9718        0.4855     0.9590 0.6446            ✅
   Tamil xlm-roberta 0.0003          32    0.9659    0.9418        0.9933     0.9657 0.9793        0.8489     0.9672 0.9042            ✅
   Tamil xlm-roberta 0.0003          64    0.9319    0.8914        0.9930     0.9248 0.9577        0.7195     0.9672 0.8252            ✅
   Tamil xlm-roberta 0.0005          32    0.8924    0.8403        0.9926     0.8775 0.9315        0.6114     0.9672 0.7492            ✅
   Tamil xlm-roberta 0.0005          64    0.9687    0.9458        0.9917     0.9706 0.9810        0.8667     0.9590 0.9105            ✅
   Tamil xlm-roberta 0.0007          32    0.9251    0.8821        0.9929     0.9167 0.9533        0.6982     0.9672 0.8110            ✅
   Tamil xlm-roberta 0.0007          64    0.9087    0.8600        0.9910     0.8987 0.9426        0.6536     0.9590 0.7774            ✅
  Telugu    mdeberta 0.0003          32    0.9651    0.9371        0.9870     0.9712 0.9791        0.8605     0.9328 0.8952           ⚠️
  Telugu    mdeberta 0.0003          64    0.8483    0.7786        0.9777     0.8387 0.9028        0.5144     0.8992 0.6544           ⚠️
  Telugu    mdeberta 0.0005          32    0.9597    0.9293        0.9901     0.9617 0.9757        0.8248     0.9496 0.8828           ⚠️
  Telugu    mdeberta 0.0005          64    0.9235    0.8750        0.9880     0.9201 0.9529        0.6914     0.9412 0.7972           ⚠️
  Telugu    mdeberta 0.0007          32    0.9477    0.9115        0.9933     0.9441 0.9681        0.7667     0.9664 0.8550            ✅
  Telugu    mdeberta 0.0007          64    0.8456    0.7831        0.9923     0.8227 0.8996        0.5088     0.9664 0.6667            ✅
  Telugu   indicbert 0.0003          32    0.9436    0.9022        0.9834     0.9489 0.9659        0.7730     0.9160 0.8385           ⚠️
  Telugu   indicbert 0.0003          64    0.1597    0.1377        0.0000     0.0000 0.0000        0.1597     1.0000 0.2755            ✅
  Telugu   indicbert 0.0005          32    0.9423    0.9030        0.9916     0.9393 0.9647        0.7500     0.9580 0.8413            ✅
  Telugu   indicbert 0.0005          64    0.7785    0.7176        0.9957     0.7396 0.8488        0.4179     0.9832 0.5865            ✅
  Telugu   indicbert 0.0007          32    0.8174    0.7546        0.9940     0.7875 0.8788        0.4659     0.9748 0.6304            ✅
  Telugu   indicbert 0.0007          64    0.8362    0.7749        0.9961     0.8083 0.8924        0.4937     0.9832 0.6573            ✅
  Telugu xlm-roberta 0.0003          32    0.8805    0.8233        0.9945     0.8626 0.9239        0.5743     0.9748 0.7227            ✅
  Telugu xlm-roberta 0.0003          64    0.8711    0.8124        0.9944     0.8514 0.9174        0.5550     0.9748 0.7073            ✅
  Telugu xlm-roberta 0.0005          32    0.9181    0.8691        0.9913     0.9105 0.9492        0.6706     0.9580 0.7889            ✅
  Telugu xlm-roberta 0.0005          64    0.9436    0.9050        0.9916     0.9409 0.9656        0.7550     0.9580 0.8444            ✅
  Telugu xlm-roberta 0.0007          32    0.7664    0.7064        0.9956     0.7252 0.8392        0.4048     0.9832 0.5735            ✅
  Telugu xlm-roberta 0.0007          64    0.9302    0.8857        0.9914     0.9249 0.9570        0.7081     0.9580 0.8143            ✅

💾 Master results saved to: /content/drive/MyDrive/Models/lora_all_results_master.csv